restarone/violet_rails

Capfile

* add rsync timeout 300 seconds
Co-authored-by: donrestarone <shashikejayatunge@gmail.co>

release: Address flakiness in rsync task in cap deploy (#380)

---

app/mailers/simple_discussion/user_mailer.rb
test/controllers/simple_discussion/forum_threads_controller_test.rb

prevent defaulting to application mailer from address, set it in the simple_discussion engine instead
(#420)

[Bug fix] set forum notification email origin explicitly

---

app/controllers/comfy/admin/web_settings_controller.rb
app/controllers/simple_discussion/forum_posts_controller.rb
app/controllers/simple_discussion/forum_threads_controller.rb
app/mailboxes/e_mailbox.rb
app/models/api_namespace.rb
app/services/api_namespace/plugin/v1/subdomain_events_service.rb
app/sidekiq/api_resource_spawn_job.rb
app/views/comfy/admin/web_settings/_form.haml
db/migrate/20220420153229_add_plugin_subdomain_events_to_api.rb
db/schema.rb
test/controllers/admin/comfy/api_resources_controller_test.rb
test/controllers/simple_discussion/forum_threads_controller_test.rb
test/fixtures/api_actions.yml
test/fixtures/api_namespaces.yml
test/fixtures/api_resources.yml
test/mailboxes/e_mailbox_test.rb
test/models/api_namespace_test.rb
test/models/subdomain_test.rb

feature request: https://github.com/restarone/violet_rails/issues/430
* add basic fixture for plugin_subdomain_events
* 
* basic implementation + test to verify that it doesnt work when it shouldnt
* hook into emailbox to create notification when emails are received
* execute create api actions
* api action payload mapping issue
* fix nesting
* add trackability to forum + add more tests
* fix tests by using the api action execution correctly
* add more assertions and be more picky about the plugin version
* refactor
Co-authored-by: donrestarone <shashikejayatunge@gmail.co>

[Feature] Add api plugin subdomain events (#433)

---

app/models/user.rb
db/seeds.rb

* fix broken seeds
* update full user permissions object with newly introduced permissions so canonical users don't get locked out
Co-authored-by: donrestarone <shashikejayatunge@gmail.co>

[bug fix] fix canonical user permissions after subdomain creation

---

app/models/external_api_client.rb
app/sidekiq/external_api_client_job.rb
test/controllers/admin/comfy/external_api_clients_controller_test.rb
test/models/external_api_client_test.rb

Prevent multiple api clients from running at the same time

Prevent multiple api clients from running at the same time

---

app/controllers/simple_discussion/forum_posts_controller.rb
app/controllers/simple_discussion/forum_threads_controller.rb
app/jobs/forum_post_notification_job.rb
app/jobs/forum_thread_notification_job.rb
app/models/external_api_client.rb
app/sidekiq/api_resource_spawn_job.rb
app/sidekiq/external_api_client_job.rb
app/views/comfy/admin/external_api_clients/show.html.haml
config/schedule.rb
db/migrate/20220430125538_add_last_run_to_external_api_client.rb
db/schema.rb
lib/tasks/external_api_client.rake
test/controllers/admin/comfy/external_api_clients_controller_test.rb
test/controllers/simple_discussion/forum_threads_controller_test.rb
test/models/external_api_client_test.rb
test/tasks/external_api_client_cron_job_test.rb

* add early return to prevent external api client job from spawning if another is running
* prevent overlapping cronjobs from running by cleaning up schedule.rb (we have a externalApiClient job discovery system that pools every minute now)
* switch forum over from using activejob to sidekiq (we need to phase out activejob since a lot of the flakiness is coming from that system). 
* fix multiple actions firing from subdomain events plugin

[bug fix release request] Prevent multiple api clients from running at the same time,  switch forum over from using activejob to sidekiq

---

app/controllers/comfy/admin/api_namespaces_controller.rb
app/controllers/comfy/admin/api_resources_controller.rb
app/controllers/concerns/api_actionable.rb
app/controllers/resource_controller.rb
app/helpers/application_helper.rb
app/models/api_action.rb
app/models/custom_api_action.rb
app/views/comfy/admin/api_actions/_form.html.haml
app/views/comfy/admin/api_actions/action_workflow.html.haml
db/migrate/20220513034804_add_method_definition_to_api_actions.rb
db/schema.rb
test/controllers/resource_controller_test.rb
test/fixtures/api_actions.yml
test/fixtures/api_forms.yml
test/fixtures/api_namespaces.yml

https://github.com/restarone/violet_rails/issues/527
when deployed to `staging`, it should
1. allow N number of custom actions to be performed 
2. log errors in the response (similar to HTTP action)
3. handle custom actions in the controller context
4. handle custom actions out of the controller context (ie; sending an email)
5. not break existing API action workflows

[violet rails core] Ability to define a custom API action (ruby method) similar to External Api Client

---

app/controllers/comfy/admin/api_namespaces_controller.rb
app/controllers/comfy/admin/api_resources_controller.rb
app/controllers/concerns/api_actionable.rb
app/controllers/resource_controller.rb
app/helpers/application_helper.rb
app/models/api_action.rb
app/models/custom_api_action.rb
app/views/comfy/admin/api_actions/_form.html.haml
app/views/comfy/admin/api_actions/action_workflow.html.haml
db/migrate/20220513034804_add_method_definition_to_api_actions.rb
db/schema.rb
test/controllers/resource_controller_test.rb
test/fixtures/api_actions.yml
test/fixtures/api_forms.yml
test/fixtures/api_namespaces.yml

@alis-khadka your changes are being tested/deployed :) :+1: 
https://github.com/restarone/violet_rails/issues/527
when deployed to `staging`, it should
1. allow N number of custom actions to be performed 
2. log errors in the response (similar to HTTP action)
3. handle custom actions in the controller context
4. handle custom actions out of the controller context (ie; sending an email)
5. not break existing API action workflows

Rc integrate custom api action

---

Gemfile
Gemfile.lock
MIT-LICENSE
app/views/comfy/admin/cms/partials/_navigation_before.haml

worked pretty good when we migrated our database from EC2 to RDS: 
https://github.com/restarone/violet_rails/issues/563 thanks @yashkir

[feature] rails based maintenance mode with turnout, [bug fix] API #show view covers edit / back buttons on certain screen sizes, update MIT license

---

app/controllers/comfy/admin/dashboard_controller.rb
app/controllers/comfy/admin/users_controller.rb
app/controllers/subdomains/base_controller.rb
app/models/user.rb
app/views/comfy/admin/users/_form.haml
app/views/comfy/admin/users/edit.haml
db/migrate/20220524080242_add_can_manage_analytics_to_users.rb
db/schema.rb
test/controllers/admin/comfy/dashboard_controller_test.rb
test/controllers/admin/comfy/users_controller_test.rb

https://github.com/restarone/violet_rails/issues/552
1. after migration, users should not be able to access analytics
2. only users with permission can_manage_analytics can access views under: `/dashboard`, `dashboard/events_list`, `dashboard/events/:event_name`, `dashboard/sessions/:session_id`, `users/:user_id/edit/sessions/:session_id`

[Feature] add permission can_manage_analytics to users for controlling analytics access

---

app/controllers/comfy/admin/api_namespaces_controller.rb
app/models/api_namespace.rb
app/views/comfy/admin/api_namespaces/show.html.haml
config/routes.rb
test/controllers/admin/comfy/api_namespaces_controller_test.rb

https://github.com/restarone/violet_rails/issues/622
1. API namespaces are accessible 
2. API namespace is duplicable 
3. 2. API namespace is duplicable with associations

[Feature] Ability to clone api namespace along with its children

---

.github/workflows/heroku-deploy.yml
Gemfile
Gemfile.lock
Procfile
app/models/user.rb
package.json

addresses: https://github.com/restarone/violet_rails/issues/385
1. EC2 deployments using an older version of Node is still possible 
2. New Node is only used on Heroku

Fix for heroku and capistrano node version (#657)

---

app/views/users/mailer/reset_password_instructions.html.haml
test/controllers/users/passwords_controller_test.rb

addresses: https://github.com/restarone/violet_rails/issues/643
1. password reset workflow works as expected in subdomain (`foo.example.com`)
2. password reset works as expected in apex domain (`example.com`)

[bug fix] password reset link is broken in apex domain

---

config/environments/production.rb
config/environments/staging.rb

ideally we should allow each system admin to choose their preferred verbosity in the error reporting service. But for now, most of the systems we are responsible for are too loud in raising the following errors:  
``` ruby
'ActionController::ParameterMissing', 
'ActionController::RoutingError',
'ActionController::InvalidAuthenticityToken',
'ActionDispatch::Http::MimeNegotiation::InvalidType',
'ActiveRecord::RecordNotFound',
```
due to crawlers and bots. To ensure that we don't miss actual issues (eg: https://github.com/restarone/violet_rails/issues/578) we should limit the amount of false-positives that are reported to our bug triaging teams

tune error reporting again to prevent getting spammed by bots

---

app/controllers/comfy/admin/dashboard_controller.rb
app/models/ahoy/event.rb
app/views/comfy/admin/dashboard/events_detail.haml
app/views/comfy/admin/external_api_clients/_form.html.haml
config/environments/production.rb
config/environments/staging.rb
config/routes.rb
test/controllers/admin/comfy/dashboard_controller_test.rb

addresses: https://github.com/restarone/violet_rails/issues/651
1. able delete visits for a given event
2. able to delete event and visits
3. does not delete visits of a event 
1. does not mutate/corrupt existing data when the form is rendered and submitted with no changes
2. renders existing data correctly
ideally we should allow each system admin to choose their preferred verbosity in the error reporting service. But for now, most of the systems we are responsible for are too loud in raising the following errors:  
``` ruby
'ActionController::ParameterMissing', 
'ActionController::RoutingError',
'ActionController::InvalidAuthenticityToken',
'ActionDispatch::Http::MimeNegotiation::InvalidType',
'ActiveRecord::RecordNotFound',
```
due to crawlers and bots. To ensure that we don't miss …

[feature] Ability to delete custom event and visits, [feature] add code editor to ExternalApiConnection

---

Gemfile
Gemfile.lock

addresses: https://github.com/restarone/violet_rails/issues/669
remove 12 factor gem, we have to make sure that we can still deploy to heroku without it-- the reason for removal is that it treats logs as event streams (we dont have an out-of-the-box solution for logging to stdout) and some clients need to write logs to disk

remove 12 factor gem to allow logging to disk

---

lib/tasks/external_api_client.rake

we push in a newly initialized subdomain named public so we can switch to it in the context block

fix data discovery issue in rake tasks (public schema is not being read)

---

app/models/user.rb
app/views/comfy/admin/users/_form.haml
test/controllers/admin/comfy/users_controller_test.rb
test/models/user_test.rb

Addresses #313 
1. delete button not shown if the user is the last admin who can manage users
2. admin cannot be deleted from the web console if they are the only one who can manage users

[Bug fix] last admin should not be able to delete themselves

---

app/controllers/comfy/admin/api_forms_controller.rb
app/controllers/resource_controller.rb
app/helpers/application_helper.rb
app/javascript/packs/application.js
app/javascript/packs/comfy/admin/cms.js
app/javascript/packs/website/call_to_actions.js
app/models/api_form.rb
app/views/comfy/admin/api_forms/_form.html.haml
app/views/comfy/admin/api_forms/_render.haml
db/migrate/20220609041057_add_show_recaptcha_v3_to_api_forms.rb
db/schema.rb
test/controllers/resource_controller_test.rb
test/helpers/application_helper_test.rb
test/models/api_form_test.rb

addresses: https://github.com/restarone/violet_rails/issues/639
1. existing forms are not broken (recaptcha v2 or none)
2. existing recaptcha v2 forms work as expected
3. if recaptcha v3 is chosen and the server is not configured for recaptcha v3 by setting environment variables `RECAPTCHA_SITE_KEY_V3` and `RECAPTCHA_SECRET_KEY_V3` the system presents a graceful error message instead of failure
4. recaptcha v3 works
5. Recaptcha V2 and V3 can both be enabled on the server and the system can use both when/where-ever needed

[feature]: Recaptcha v3 option in API form (#702)

---

app/controllers/mailbox/message_threads_controller.rb
app/mailers/e_mailer.rb
app/views/mailbox/message_threads/_form.haml
test/mailers/e_mailer_test.rb

resolves #149 
- connected select2 to recipients field
- previous `EMailer.ship` attempted to send separate email for each recipient, only the last recipient was being sent to
- EMailer now correctly fills the recipients array

allow multiple recipients for emails with select2

---

app/controllers/mailbox/message_threads_controller.rb
app/mailers/e_mailer.rb
app/views/mailbox/message_threads/_form.haml
test/mailers/e_mailer_test.rb

resolves #149 
- connected select2 to recipients field
- previous `EMailer.ship` attempted to send separate email for each recipient, only the last recipient was being sent to
- EMailer now correctly fills the recipients array
Co-authored-by: Yuriy Yashkir <yuriy.yashkir@gmail.com>

[feature] allow multiple recipients in email

---

test/controllers/admin/comfy/external_api_clients_controller_test.rb
test/fixtures/external_api_clients.yml

addresses: https://github.com/restarone/violet_rails/issues/694 & https://github.com/restarone/violet_rails/issues/738

[CI] add tests for ExternalApiClientsController, [plugin] create VacuumJob plugin for ExternalApiClient/Connection

---

app/controllers/mailbox/mailbox_controller.rb
app/models/message.rb
app/models/message_thread.rb
app/views/mailbox/mailbox/_pagination.haml
app/views/mailbox/mailbox/_search_filters.haml
app/views/mailbox/mailbox/show.haml
test/controllers/mailbox/mailbox_controller_test.rb

Addresses: https://github.com/restarone/violet_rails/issues/777
https://user-images.githubusercontent.com/35935196/174919097-eaca5e9d-61cc-4ade-9647-bab7355a3ecd.mp4
* [Violet Rails Core] add pagination + search to email threads/index (#788)
* feat(): implementation for pagination and searching by email-body, subject or sender-email adrress in mailbox
* feat(): added test cases
* feat(): add functionality to search my recipients email (#794)

[feature] add pagination + search to email threads/index

---

Dockerfile.dev

1. downgrade to ruby 2.6.6 for dev, since we run it in production its important we catch issues early on.

revert ruby 3 docker dev

---

Dockerfile.dev
app/views/comfy/admin/cms/partials/_navigation_before.haml
app/views/comfy/admin/cms/partials/_navigation_inner.haml
test/controllers/admin/comfy/users_controller_test.rb
test/test_helper.rb

Deploy not necessary (but will do once RC is packaged)
1. downgrade to ruby 2.6.6 for dev, since we run it in production its important we catch issues early on.  @donrestarone 
2. remove model filter from test coverage @Pralish 
3. https://github.com/restarone/violet_rails/issues/384 by @Gloria-kuang

revert ruby 3 docker dev, remove model filter from test coverage, when feature is un-enabled remove buttons related to it

---

app/helpers/application_helper.rb
app/javascript/packs/application.js
app/views/layouts/comfy/blog/application.html.erb
app/views/layouts/devise.html.haml
app/views/layouts/simple_discussion.html.erb

https://github.com/restarone/violet_rails/issues/817
iOS project: https://github.com/restarone/violet_rails_ios_client
replace `{{ cms:snippet navbar }}` and `{{ cms:snippet footer }}` with `{{cms:helper render_smart_navbar}}` and `{{cms:helper render_smart_footer}}`. These new functions will intelligently render navbar/footer as `{{ cms:snippet navbar }}` and `{{ cms:snippet footer }}` for web clients. We don't want to show web navigation on native clients
Your Violet Rails app will now look like this on iOS
web navbar is not shown, instead a system tray is shown at the bottom with relevant navigation buttons

make server turbo native ready

---

app/helpers/application_helper.rb
app/javascript/packs/application.js
app/views/layouts/comfy/blog/application.html.erb
app/views/layouts/devise.html.haml
app/views/layouts/simple_discussion.html.erb

resolves: https://github.com/restarone/violet_rails/issues/817
iOS project: https://github.com/restarone/violet_rails_ios_client
replace `{{ cms:snippet navbar }}` and `{{ cms:snippet footer }}` with `{{cms:helper render_smart_navbar}}` and `{{cms:helper render_smart_footer}}`. These new functions will intelligently render navbar/footer as `{{ cms:snippet navbar }}` and `{{ cms:snippet footer }}` for web clients. We don't want to show web navigation on native clients
Your Violet Rails app will now look like this on iOS
web navbar is not shown, instead a system tray is shown at the bottom with relevant navigation buttons

[feature] make server turbo native ready

---

.github/workflows/ruby.yml

Addresses: https://github.com/restarone/violet_rails/issues/815
If we click on one of the link of artifact, a zip folder _(coverage folder)_ is downloaded. Within the folder, we can view the _index.html_ file.
https://user-images.githubusercontent.com/25191509/175912039-18e8d52e-7bbd-4850-b50a-67869d399fa6.mp4
artifacts will clear after 90 days by default. 
[reference](https://github.com/actions/upload-artifact#retention-period)
credits @alis-khadka

[CI] Save code coverage as artifact (#828)

---

.github/workflows/ruby.yml

Addresses: https://github.com/restarone/violet_rails/issues/815
If we click on one of the link of artifact, a zip folder _(coverage folder)_ is downloaded. Within the folder, we can view the _index.html_ file.
https://user-images.githubusercontent.com/25191509/175912039-18e8d52e-7bbd-4850-b50a-67869d399fa6.mp4
artifacts will clear after 90 days by default. 
[reference](https://github.com/actions/upload-artifact#retention-period)
credits @alis-khadka 

[CI] Save code coverage as artifact

---

app/controllers/simple_discussion/forum_posts_controller.rb
app/controllers/simple_discussion/forum_threads_controller.rb
test/controllers/simple_discussion/forum_posts_controller_test.rb
test/controllers/simple_discussion/forum_threads_controller_test.rb

RCA:
This issue seems to have started after we introduced hotwire-turbo in violet-rails.
Turbo expects 303(redirection) for form submission and 4xx/5xx to show validation errors in form.
Previously, when creating/updating of post/thread fails, we were not specifying status_code for the response.
https://turbo.hotwired.dev/handbook/drive#redirecting-after-a-form-submission
https://user-images.githubusercontent.com/35935196/176429422-cd40c98f-9ff3-49fa-a5cd-a64d21fcb283.mp4

[Bug Fix]: forum post/thread creation errors are not showing

---

Capfile
app/controllers/simple_discussion/forum_posts_controller.rb
app/controllers/simple_discussion/forum_threads_controller.rb
config/deploy/production.rb
config/deploy/staging.rb
test/controllers/simple_discussion/forum_posts_controller_test.rb
test/controllers/simple_discussion/forum_threads_controller_test.rb

resolves: https://github.com/restarone/violet_rails/issues/338
RCA:
This issue seems to have started after we introduced hotwire-turbo in violet-rails.
Turbo expects 303(redirection) for form submission and 4xx/5xx to show validation errors in form.
Previously, when creating/updating of post/thread fails, we were not specifying status_code for the response.
https://turbo.hotwired.dev/handbook/drive#redirecting-after-a-form-submission
https://user-images.githubusercontent.com/35935196/176429422-cd40c98f-9ff3-49fa-a5cd-a64d21fcb283.mp4
resolves: https://github.com/restarone/violet_rails/issues/338

[Bug Fix]: forum post/thread creation errors are not showing, [Bug Fix] fix rsync flakiness in deploy action

---

config/initializers/devise.rb
test/controllers/users/registrations_controller_test.rb
test/controllers/users/sessions_controller_test.rb

Addresses: https://github.com/restarone/violet_rails/issues/842
The bug existed in _sign-in_, _sign-up_, and _users/edit_ page. You can view it in the attached video below.
﻿
https://user-images.githubusercontent.com/25191509/176618871-e3e9c2b5-b6bd-4dfb-a59b-80e9ccfecf0b.mp4
The following reference is used to patch this bug.
[https://github.com/hotwired/turbo/issues/45](https://github.com/hotwired/turbo/issues/45)
And, below is the demo video after the fix.
https://user-images.githubusercontent.com/25191509/176619214-bf10ce2c-60be-44ce-bfe8-ed97c9930dff.mp4
﻿

[Bug] Devise login forms do not show correct error messages

---

config/initializers/active_support.rb
config/initializers/devise.rb
test/controllers/users/registrations_controller_test.rb
test/controllers/users/sessions_controller_test.rb

Addresses: https://github.com/restarone/violet_rails/issues/842
The bug existed in _sign-in_, _sign-up_, and _users/edit_ page. You can view it in the attached video below.
﻿
https://user-images.githubusercontent.com/25191509/176618871-e3e9c2b5-b6bd-4dfb-a59b-80e9ccfecf0b.mp4
The following reference is used to patch this bug.
[https://github.com/hotwired/turbo/issues/45](https://github.com/hotwired/turbo/issues/45)
And, below is the demo video after the fix.
https://user-images.githubusercontent.com/25191509/176619214-bf10ce2c-60be-44ce-bfe8-ed97c9930dff.mp4
Reference: https://github.com/rails/rails/issues/37672
Addresses: https://github.com/restarone/violet_rails/pull/852

[Bug fix] Devise login forms do not show correct error messages

---

app/controllers/comfy/admin/api_namespaces_controller.rb
app/models/non_primitive_property.rb
app/views/comfy/admin/api_forms/_render.haml
app/views/comfy/admin/api_namespaces/_form.html.haml
app/views/comfy/admin/non_primitive_properties/_nested_form.haml
db/migrate/20220628050113_add_allow_attachments_to_non_primitive_properties.rb
db/schema.rb
test/models/non_primitive_property_test.rb

Addresses: https://github.com/restarone/violet_rails/issues/661
https://user-images.githubusercontent.com/35935196/176429682-a19cc7b7-f692-4f18-8bc9-7f95947fc9b2.mp4
Unchecked checkbox not passing false to params:
It took me some time to figure this out. In the end, I followed these reference for the workaround;
https://github.com/rails/rails/issues/5937
https://stackoverflow.com/questions/20379311/how-to-get-blank-checkboxes-to-pass-as-false-to-params/20380051#20380051

[feature] ability to toggle trix editor attachments

---

app/controllers/comfy/admin/api_namespaces_controller.rb
app/mailers/api_action_mailer.rb
app/models/api_action.rb
app/models/concerns/dynamic_attribute.rb
app/models/concerns/safe_executable_validator.rb
app/views/api_action_mailer/send_email.html.erb
app/views/comfy/admin/api_actions/_form.html.haml
app/views/comfy/admin/api_actions/action_workflow.html.haml
app/views/comfy/admin/api_actions/index.html.haml
app/views/comfy/admin/api_actions/show.html.haml
app/views/comfy/admin/api_namespaces/show.html.haml
app/views/comfy/admin/api_resources/show.html.haml
app/views/comfy/admin/external_api_clients/index.html.haml
config/environments/development.rb
db/migrate/20220609092515_add_email_subject_to_api_actions.rb
db/schema.rb
test/models/api_action_test.rb
test/models/concerns/dynamic_attribute_test.rb
test/models/external_api_client_test.rb

This change adds dynamic segments in Email and Web Request Actions in the API Namespace / API Actions sub-systems.
addresses: https://github.com/restarone/violet_rails/issues/653
addresses: https://github.com/restarone/violet_rails/issues/652
upgrade path: https://github.com/restarone/violet_rails/issues/836
Given a simple form like this: 
an email like this is triggered: 
the system will generate the email message: 
Now you have dynamic segments in the request URL
Every API Action is tracked by Violet Rails, and you can see what the system did after it evaluated your code. 
The above action  resulted in the following email: 
The same evaluation rules apply to HTTP actions, so you can see exactly what was sent to external systems -- for example:

[feature] Dynamic attributes in API Actions

---

app/controllers/concerns/api_actionable.rb
test/controllers/resource_controller_test.rb

Addresses: https://github.com/restarone/violet_rails/issues/789

[bug fix] Cannot define a custom success/fail message without setting up a redirect action

---

app/views/comfy/admin/api_actions/_form.html.haml

[bug fix] handle textarea overflow in send_email API action 

---

app/views/comfy/admin/api_actions/_form.html.haml

[bug fix] handle textarea overflow in send_email API action

---

app/views/comfy/admin/cms/partials/_navigation_inner.haml
app/views/comfy/admin/users/index.html.haml
config/locales/views/comfy/web_settings/en.yml
test/controllers/admin/comfy/users_controller_test.rb

To keep the UI in-line with current features. namely iPhone support since release: https://github.com/restarone/violet_rails/releases/tag/0.9.5

rename Web Settings to App Settings

---

app/controllers/comfy/admin/api_actions_controller.rb
app/controllers/concerns/api_actionable.rb
app/models/api_action.rb
app/models/concerns/dynamic_attribute.rb
app/models/current.rb
app/views/comfy/admin/api_actions/show.html.haml
test/controllers/resource_controller_test.rb

Addresses: https://github.com/restarone/violet_rails/issues/457

[feature] Pass current user and current visit to api data pipeline

---

app/controllers/comfy/admin/api_namespaces_controller.rb
app/controllers/concerns/api_actionable.rb
app/controllers/resource_controller.rb
app/models/api_action.rb
app/models/concerns/dynamic_attribute.rb
app/views/comfy/admin/api_actions/_form.html.haml
app/views/comfy/admin/api_actions/action_workflow.html.haml
app/views/comfy/admin/api_actions/show.html.haml
db/migrate/20220707090412_add_redirect_type_to_api_actions.rb
db/schema.rb
test/controllers/resource_controller_test.rb

This feature allows Ruby evaluation in the redirect action so you can do conditional redirects and other fanciness: 
---
The implicit return value of the evaluated statement should be a valid path in the application. As illustrated above, you can use an absolute path (like: `'/'`, or a Rails route helper like `dashboard_path`)
---
Addresses: https://github.com/restarone/violet_rails/issues/873
https://user-images.githubusercontent.com/35935196/178011977-82aab515-87b5-49a3-8591-f8ba3535d9eb.mp4

[feature] Allow dynamic segment in api redirect action 

---

.github/workflows/deploy.yml
app/controllers/comfy/admin/api_namespaces_controller.rb
app/controllers/concerns/api_actionable.rb
app/controllers/resource_controller.rb
app/models/api_action.rb
app/models/concerns/dynamic_attribute.rb
app/views/comfy/admin/api_actions/_form.html.haml
app/views/comfy/admin/api_actions/action_workflow.html.haml
app/views/comfy/admin/api_actions/show.html.haml
db/migrate/20220707090412_add_redirect_type_to_api_actions.rb
db/schema.rb
test/controllers/resource_controller_test.rb

This feature allows Ruby evaluation in the redirect action so you can do conditional redirects and other fanciness: 
---
The implicit return value of the evaluated statement should be a valid path in the application. As illustrated above, you can use an absolute path (like: `'/'`, or a Rails route helper like `dashboard_path`)
---
Addresses: https://github.com/restarone/violet_rails/issues/873
https://user-images.githubusercontent.com/35935196/178011977-82aab515-87b5-49a3-8591-f8ba3535d9eb.mp4
Co-authored-by: Prashant Khadka <prashant.khadka052@gmail.com>

[feature] Allow dynamic segment in API redirect action

---

test/fixtures/api_namespaces.yml
test/fixtures/api_resources.yml
test/fixtures/external_api_clients.yml
test/plugins/mailchimp_plugin_test.rb

https://gist.github.com/restarone-solutions/5ac432cd98b1015b658c914399d2e44c
Documentation: https://github.com/restarone/violet_rails/issues/720 ([see here for V2](https://github.com/restarone/violet_rails/issues/720#issuecomment-1183585540))

add tests for mailchimp plugin (#893)

---

app/views/comfy/admin/api_namespaces/show.html.haml
test/controllers/admin/comfy/api_namespaces_controller_test.rb

Addresses: https://github.com/restarone/violet_rails/issues/871
**Demo:**
https://user-images.githubusercontent.com/25191509/179969416-1d807c22-9c82-46d1-91b9-bc27bbdbce2c.mp4
**Mobile**
https://user-images.githubusercontent.com/25191509/180193220-563d3c31-352d-491c-91f1-c32ccfaa54ab.mp4
* feat(): refactoring test case
* feat(): make api-resources index table responsive
* feat(): making table pagination fixed when the table is scrollable
Co-authored-by: Prashant Khadka <prashant.khadka052@gmail.com>

[feature] show dynamic attributes in API Resources index table (#945)

---

app/controllers/concerns/api_actionable.rb
app/helpers/ahoy_events_helper.rb
app/models/ahoy/event.rb
app/models/api_resource.rb
app/views/comfy/admin/api_namespaces/_editor.haml
app/views/comfy/admin/api_resources/show.html.haml
test/controllers/resource_controller_test.rb
test/helpers/ahoy_events_helper_test.rb
test/models/api_resource_test.rb

Addresses: https://github.com/restarone/violet_rails/issues/900 by @Pralish 
https://user-images.githubusercontent.com/35935196/180570997-d3ebd298-0972-4e01-9a36-9b44dfe2528d.mov
Addresses #848 by @Ayon95

[feature] attach current_visit and current_user to created API Resource, [feature] Render rich text or file content on a new line in API

---

app/controllers/api/resource_controller.rb
app/graphql/types/api_namespace_type.rb
app/models/api_resource.rb
app/models/concerns/jsonb_search/query_builder.rb
app/models/concerns/jsonb_search/searchable.rb
test/controllers/api/resource_controller_test.rb
test/controllers/graphql_controller_test.rb
test/models/concerns/jsonb_search/query_builder_test.rb

Addresses: https://github.com/restarone/violet_rails/issues/888
Allows `PARTIAL` and `EXACT` match querying
https://user-images.githubusercontent.com/35935196/180443733-61e75634-5f86-4777-a21f-7959a5cff734.mov
https://user-images.githubusercontent.com/35935196/180443718-721d97c9-f2ab-418e-af7f-23c3c5faa66e.mov
``` gql
{ 
apiNamespaces(slug: "support_request") { 
id 
apiResources(properties: {
product:{ option: "PARTIAL", value: "nikean" }
}) {
id
properties
}
} 
}
```

[Feature] Allow querying in REST API and GraphQL

---

app/helpers/content_helper.rb
test/fixtures/comfy/cms/snippets.yml
test/helpers/content_helper_test.rb

Addresses: https://github.com/restarone/violet_rails/issues/271
https://user-images.githubusercontent.com/35935196/183777190-e9c330e1-f89a-4751-a34f-4a8de1abda23.mov
1. Create a snippet with the content you want:
2. Pass the snippet identifier to the `logged_in_user_render` function: 
3. Result 🥳

[feature] Conditional render snippet based on user session

---

app/controllers/concerns/api_actionable.rb
app/controllers/resource_controller.rb
app/views/comfy/admin/api_forms/_render.haml
app/views/shared/reset_recaptcha_with_error.js.erb
test/controllers/resource_controller_test.rb

This reverts commit a6806aa4d90bb7edc2ca380a2a3a6a99f5538398.
PR that introduced the change: https://github.com/restarone/violet_rails/pull/1019
https://user-images.githubusercontent.com/35935196/184727578-d5c68a4b-bab6-4314-8511-7d429faaf685.mov
Co-authored-by: donrestarone <shashikejayatunge@gmail.com>

revert [feature] rerender recaptcha if recaptcha verification fails

---

Procfile
config/puma.rb

Addresses: https://github.com/restarone/violet_rails/issues/665
set environment variable `INLINE_SIDEKIQ_WITH_PUMA` to `true` in Heroku.

[feature] Run sidekiq in forked process on Heroku dyno

---

Procfile
config/puma.rb

Addresses: https://github.com/restarone/violet_rails/issues/665
set environment variable `INLINE_SIDEKIQ_WITH_PUMA` to `true` in Heroku.

[feature] Run sidekiq in forked process on Heroku dyno (#1032)

---

Procfile
config/puma.rb

Addresses: https://github.com/restarone/violet_rails/issues/665
set environment variable `INLINE_SIDEKIQ_WITH_PUMA` to `true` in Heroku.

[feature] Run sidekiq in forked process on Heroku dyno (#1032) (#1034)

---

Gemfile
Gemfile.lock
config/initializers/sidekiq.rb
config/sidekiq.yml

Make sure that each Violet Rails application is reading off a namespace so multiple apps can share Redis infrastructure (eg: AWS Elasticache). 
resolves: https://github.com/restarone/violet_rails/issues/904 & https://github.com/restarone/violet_rails/issues/536
1. Sending / receiving emails :heavy_check_mark: 
2. Ahoy geocode / analytics :heavy_check_mark: 
3. file uploads :heavy_check_mark: 
4. file previews :heavy_check_mark: 
5. forum
6. API forms (file upload, rich text) :heavy_check_mark: 
7. ruby automation :heavy_check_mark: 
8. API actions fired from the model by BishopTlsMonitoring and BishopMonitoring (External API Connection  #623) should work (eg sending HTTP requests / emails) ✔️  -- adding automated tests in hopes of detecting this regression in CI: …

[feature] namespace sidekiq + add queues

---

app/views/comfy/admin/api_namespaces/export_api_resources.csv.haml
test/controllers/admin/comfy/api_namespaces_controller_test.rb

Addresses: https://github.com/restarone/violet_rails/issues/1061
**Demo**
https://user-images.githubusercontent.com/25191509/187054661-bd5c209b-58ba-4564-8f0b-338a6f864858.mp4

[Violet Rails Core]: Include non primitive types in api resource csv export

---

app/controllers/comfy/admin/api_resources_controller.rb
app/controllers/concerns/api_actionable.rb
app/controllers/resource_controller.rb
app/views/comfy/admin/api_resources/_form.html.haml
test/controllers/admin/comfy/api_resources_controller_test.rb
test/controllers/resource_controller_test.rb

Addresses: https://github.com/restarone/violet_rails/issues/949 and https://github.com/restarone/violet_rails/issues/1043
**Demo for creating an API resource from admin results in broken page**
https://user-images.githubusercontent.com/25191509/187018834-7f2ca39f-2020-4755-b0c5-74aebb856380.mp4
**Demo for API form success flash message randomly showing in admin UI**
https://user-images.githubusercontent.com/25191509/187018864-32ed9a84-fa01-4040-b8b7-9bbc954771d9.mp4

[Bug fix]: API form success flash message randomly showing in admin UI & creating an API resource from admin results in broken page

---

app/helpers/content_helper.rb
app/models/concerns/jsonb_search/query_builder.rb
test/helpers/content_helper_test.rb
test/models/concerns/jsonb_search/query_builder_test.rb

Addresses: https://github.com/restarone/violet_rails/issues/267, https://github.com/restarone/violet_rails/pull/1047#issuecomment-1249379969
Returns records that contains both of given values
`render_api_namespace_resource_index(@api_namespace.slug, { 'scope' => { 'properties' => { 'tags': { 'value': ['not action', 'comedy'], option: 'PARTIAL', match: 'ALL'} } } })`
Returns records that contains atleast one of given values
`render_api_namespace_resource_index(@api_namespace.slug, { 'scope' => { 'properties' => { 'tags': { 'value': ['not action', 'comedy'], option: 'PARTIAL', match: 'ANY'} } } })`
`render_api_namespace_resource_index(@api_namespace.slug, { 'limit': 10 })`

Api HTML renderer: Allow ALL/ANY match on array + limit resources

---

app/helpers/content_helper.rb
app/models/concerns/jsonb_search/query_builder.rb
test/helpers/content_helper_test.rb
test/models/concerns/jsonb_search/query_builder_test.rb

Addresses: https://github.com/restarone/violet_rails/issues/267, https://github.com/restarone/violet_rails/pull/1047#issuecomment-1249379969
Returns records that contains both of given values `render_api_namespace_resource_index(@api_namespace.slug, { 'scope' => { 'properties' => { 'tags': { 'value': ['not action', 'comedy'], option: 'PARTIAL', match: 'ALL'} } } })`
Returns records that contains atleast one of given values `render_api_namespace_resource_index(@api_namespace.slug, { 'scope' => { 'properties' => { 'tags': { 'value': ['not action', 'comedy'], option: 'PARTIAL', match: 'ANY'} } } })`
`render_api_namespace_resource_index(@api_namespace.slug, { 'limit': 10 })`

[feature] API renderer Allow ALL/ANY + limit resources (#1117)

---

app/mailers/e_mailer.rb
app/services/violet/connection.rb
test/fixtures/api_namespaces.yml
test/fixtures/api_resources.yml
test/fixtures/external_api_clients.yml
test/plugins/compliance_visitor_data_request_plugin_test.rb

Addresses #1073 
When a visitor submits a data request form, this plugin will send an email with CSV attachments (one attachment per API namespace that has visitor-submitted data) to that visitor.
An external API connection with this plugin should be set up for the API namespace that has the form for submitting data request.
Message thread with attachments:
Email with attachments:
EXCLUDE_API_NAMESPACES: an array of slugs of API namespaces that will be excluded
MESSAGE: the message that will be used in the email body
SCAN_ALL_NAMESPACES: a boolean indicating whether or not all API namespaces should be scanned
- if `EXCLUDE_API_NAMESPACES` is omitted or if it's an empty array, then `SCAN_ALL_NAMESPACES` should be provided and its value should be `true`
- `SCAN_ALL_NAMESPACES` should be …

[feature] Compliance visitor data request plugin

---

app/models/concerns/dynamic_attribute.rb
test/helpers/content_helper_test.rb

Addresses: https://github.com/restarone/violet_rails/issues/1109 
Screenshots:
Co-authored-by: Sushmit Rajaure <Sushmit@Sushmits-MacBook-Pro.local>

[feature] Allow active support / view helpers in API Renderer. (#1136)

---

app/helpers/content_helper.rb
app/models/concerns/jsonb_search/query_builder.rb
app/models/concerns/jsonb_search/searchable.rb
test/models/concerns/jsonb_search/query_builder_test.rb

Addresses: [#1137](https://github.com/restarone/violet_rails/issues/1137)
Screenshot:
Passing the third argument, ``'ANY'``  in ``build_jsonb_query`` or ``jsonb_search`` method will generate the clause requiring only one condition to be satisfied.

[feature] API resource query match any one condition

---

app/helpers/content_helper.rb
app/models/concerns/jsonb_search/query_builder.rb
app/models/concerns/jsonb_search/searchable.rb
test/models/concerns/jsonb_search/query_builder_test.rb

Addresses: [#1137](https://github.com/restarone/violet_rails/issues/1137)
Screenshot:
Passing the third argument, ``'ANY'``  in ``build_jsonb_query`` or ``jsonb_search`` method will generate the clause requiring only one condition to be satisfied. 
https://user-images.githubusercontent.com/18470532/194049679-a9ea69cf-4af7-4902-a371-31a51c7ae0bf.mov
https://user-images.githubusercontent.com/18470532/194049874-3987e65b-b656-4b51-91f1-13e3476018ef.mp4
- Render the snippet on any page with this helper: {{cms:helper render_api_namespace_resource_index 'identifier'}} [Details](https://github.com/restarone/violet_rails/releases/tag/0.9.43).
- Can be used on query params, eg: [http://lvh.me:5250/?properties={"property": "value","another_property":"value"}&match=ANY]()
To filter satisfying any one …

[feature] API resource query match any one condition (#1145)

---

app/helpers/content_helper.rb
app/models/concerns/jsonb_search/query_builder.rb
app/models/concerns/jsonb_search/searchable.rb
test/models/concerns/jsonb_search/query_builder_test.rb

Addresses: [#1137](https://github.com/restarone/violet_rails/issues/1137)
Screenshot:
Passing the third argument, ``'ANY'``  in ``build_jsonb_query`` or ``jsonb_search`` method will generate the clause requiring only one condition to be satisfied. 
https://user-images.githubusercontent.com/18470532/194049679-a9ea69cf-4af7-4902-a371-31a51c7ae0bf.mov
https://user-images.githubusercontent.com/18470532/194049874-3987e65b-b656-4b51-91f1-13e3476018ef.mp4
- Render the snippet on any page with this helper: {{cms:helper render_api_namespace_resource_index 'identifier'}} [Details](https://github.com/restarone/violet_rails/releases/tag/0.9.43).
- Can be used on query params, eg: [http://lvh.me:5250/?properties={"property": "value","another_property":"value"}&match=ANY]()
To filter satisfying any one …

[feature] API resource query match any one condition (#1145) (#1146)

---

test/fixtures/api_namespaces.yml
test/fixtures/external_api_clients.yml
test/plugins/unique_string_aggregator_plugin_test.rb

Addresses #1084
This plugin takes an array of strings and creates a list of API resources (one per unique string value) for an output API namespace. For example, for two arrays - `tags: ["animation", "family", "martial arts"]`,`tags: ["animation", "family"]`  - in `movies` API namespace, 3 API resources will be created under `movie_tags` (the output API namespace in this case):
```ruby
{ "tags" => "animation", "representation" => "Animation" },
{ "tags" => "family", "representation" => "Family" },
{ "tags" => "martial arts", "representation" => "Martial Arts" }
```
https://user-images.githubusercontent.com/73725297/192908391-21560b30-1977-4451-ae15-5564d4289eb4.mp4
The following metadata properties are required:
- `INPUT_PROPERTY`: the name of the property that is mapped to an array of …

[feature] Unique string aggregator plugin (#1133)

---

test/fixtures/api_namespaces.yml
test/fixtures/external_api_clients.yml
test/plugins/unique_string_aggregator_plugin_test.rb

Addresses #1084
This plugin takes an array of strings and creates a list of API resources (one per unique string value) for an output API namespace. For example, for two arrays - `tags: ["animation", "family", "martial arts"]`,`tags: ["animation", "family"]`  - in `movies` API namespace, 3 API resources will be created under `movie_tags` (the output API namespace in this case):
```ruby
{ "tags" => "animation", "representation" => "Animation" },
{ "tags" => "family", "representation" => "Family" },
{ "tags" => "martial arts", "representation" => "Martial Arts" }
```
https://user-images.githubusercontent.com/73725297/192908391-21560b30-1977-4451-ae15-5564d4289eb4.mp4
The following metadata properties are required:
- `INPUT_PROPERTY`: the name of the property that is mapped to an array of …

[feature] Unique string aggregator plugin (#1133) (#1143)

---

test/fixtures/api_namespaces.yml
test/fixtures/api_resources.yml
test/fixtures/external_api_clients.yml
test/plugins/transcript_parser_plugin_test.rb

Addresses #1120 
This plugin takes a video transcript and generates a clean version of it by removing numbers, timestamps, and names. Given a transcript like this:
```
1
00:00:00,300 --> 00:00:02,167
[sally]: i'm in los angeles and
2
00:00:01,920 --> 00:00:02,102
[bobby]: okay
3
00:00:03,151 --> 00:00:04,737
[sally]: maybe possibly
4
00:00:05,780 --> 00:00:13,613
[bobby78]: $ oh maybe ye so nice an is a
supporter financial supporter of hollows
5
00:00:13,345 --> 00:00:15,510
[sally]: 10 s yeah
10 hello world
hi there
$10 in my wallet
```
The plugin will parse the transcript and generate a clean version of it:
```
i'm in los angeles and okay maybe possibly $ oh maybe ye so nice an is a supporter financial supporter of hollows 10 s yeah 10 hello world hi 
there $10 in my wallet
```
The …

Transcript parser plugin

---

test/fixtures/api_namespaces.yml
test/fixtures/api_resources.yml
test/fixtures/external_api_clients.yml
test/plugins/transcript_parser_plugin_test.rb

Addresses #1120 
This plugin takes a video transcript and generates a clean version of it by removing numbers, timestamps, and names. Given a transcript like this:
```
1
00:00:00,300 --> 00:00:02,167
[sally]: i'm in los angeles and
2
00:00:01,920 --> 00:00:02,102
[bobby]: okay
3
00:00:03,151 --> 00:00:04,737
[sally]: maybe possibly
4
00:00:05,780 --> 00:00:13,613
[bobby78]: $ oh maybe ye so nice an is a
supporter financial supporter of hollows
5
00:00:13,345 --> 00:00:15,510
[sally]: 10 s yeah
10 hello world
hi there
$10 in my wallet
```
The plugin will parse the transcript and generate a clean version of it:
```
i'm in los angeles and okay maybe possibly $ oh maybe ye so nice an is a supporter financial supporter of hollows 10 s yeah 10 hello world hi 
there $10 in my wallet
```
The …

[feature] Transcript parser plugin (#1121)

---

config/initializers/force_ssl.rb

Addresses: [#1149](https://github.com/restarone/violet_rails/issues/1149)
- Add config to load assets over https for staging and production.

[feature] enforce loading assets over https

---

config/initializers/force_ssl.rb

Addresses: [#1149](https://github.com/restarone/violet_rails/issues/1149)
- Add config to load assets over https for staging and production.
Co-authored-by: Regaron <Regaron@users.noreply.github.com>

[feature] enforce loading assets over https (#1158)

---

.buildpacks
.github/workflows/dokku-deploy.yml
Procfile
bin/ci-pre-deploy

Addresses: https://github.com/restarone/violet_rails/issues/1127
- The base branch of the PR needs to be `master`/`dev`/`rc` for the dokku CI to run.
- The url of the new review-app will be: `review-[PR number].violet-test.net`. A comment will be added after the deployment of review-app is successful as in image below: ![image](https://user-images.githubusercontent.com/25191509/198102327-b0153d57-48fb-433f-af0f-e3b5476f9489.png)
- Since the database of review-app is a clone of database of heroku's violet-rails, you can use the same login credentials used in heroku to login.
- While creating the PR which has label: `deploy-review-app`
- When a closed PR with label: `deploy-review-app` is reopened
- While labeling the open PR with `deploy-review-app`
- When new commits are pushed to the …

[feature] Dokku integration for testnet (#1172)

---

app/controllers/comfy/admin/api_namespaces_controller.rb
app/models/api_namespace.rb
app/views/comfy/admin/api_namespaces/index.html.haml
app/views/comfy/admin/api_namespaces/show.html.haml
test/controllers/admin/comfy/api_namespaces_controller_test.rb
test/models/api_namespace_test.rb

* [feature] link to associated CMS entity in API
Addresses: https://github.com/restarone/violet_rails/issues/974
**Demo**
https://user-images.githubusercontent.com/25191509/199165299-25d1e0fb-0cd1-49a4-8e66-224bca2fa660.mov
* feat(): sortable by CMS associations in api-namespaces/index view
* feat(): show snippets used under API HTML renderer as associated cms-entities
* feat(): fix for some API HTML renderer not being detected in CMS associations

[feature] link to associated CMS entity in API (#1189)

---

app/controllers/comfy/admin/web_settings_controller.rb
app/mailers/simple_discussion/user_mailer.rb
app/models/subdomain.rb
app/views/comfy/admin/web_settings/_form.haml
db/migrate/20221025072655_add_email_strategy_to_subdomain.rb
db/migrate/20221104133642_add_email_notification_strategy_to_subdomain.rb
db/schema.rb
test/mailers/simple_discussion/user_mailer_test.rb
test/models/subdomain_test.rb

Addresses : https://github.com/restarone/violet_rails/issues/1169
Changes : 
- Migration script added
- Test cases added
- Logic added to check boolean to set mailer address. ( Own or Restarone email)
Demo video :
https://user-images.githubusercontent.com/39255317/198045816-b7ee4333-e5a3-4875-9a18-0ed5be1f9df4.mov

Option added in settings to use own or restarone email for forum notifications.

---

app/controllers/comfy/admin/web_settings_controller.rb
app/mailers/simple_discussion/user_mailer.rb
app/models/subdomain.rb
app/views/comfy/admin/web_settings/_form.haml
db/migrate/20221104133642_add_email_notification_strategy_to_subdomain.rb
db/schema.rb
test/mailers/simple_discussion/user_mailer_test.rb
test/models/subdomain_test.rb

* [feature] ability to define forum email notification strategy
Addresses : https://github.com/restarone/violet_rails/issues/1169
Demo video :
https://user-images.githubusercontent.com/39255317/198045816-b7ee4333-e5a3-4875-9a18-0ed5be1f9df4.mov
Co-authored-by: Sushmit Rajaure <Sushmit@Sushmits-MacBook-Pro.local>
* fix(): email notification strategy implemented also while creating new forum thread
Co-authored-by: Sushmit Rajaure <Sushmit@Sushmits-MacBook-Pro.local>

[feature] ability to define forum email notification strategy (#1223)

---

app/helpers/content_helper.rb
test/helpers/content_helper_test.rb

Addresses #1122
The `snippet` option needs to be provided in order to render a snippet other than the default index or show snippet. The default snippet will be rendered if `snippet` option is not provided.
An alternative snippet `movies-staging` for `movies` API namespace can be rendered in the following way:
```ruby
{{ cms:helper render_api_namespace_resource_index 'movies', { snippet: 'movies-staging' } }}
```
An alternative snippet `movies-staging-show` for `movies` API namespace can be rendered in the following way:
```ruby
{{ cms:helper render_api_namespace_resource 'movies', { snippet: 'movies-staging' } }}
```
https://user-images.githubusercontent.com/73725297/204227285-863ccc4a-536b-425d-865c-959e1f4e10bd.mp4

Ability to associate multiple snippets with API #show and #index

---

app/helpers/content_helper.rb
test/helpers/content_helper_test.rb

Addresses #1122
The `snippet` option needs to be provided in order to render a snippet other than the default index or show snippet. The default snippet will be rendered if `snippet` option is not provided.
An alternative snippet `movies-staging` for `movies` API namespace can be rendered in the following way:
```ruby
{{ cms:helper render_api_namespace_resource_index 'movies', { snippet: 'movies-staging' } }}
```
An alternative snippet `movies-staging-show` for `movies` API namespace can be rendered in the following way:
```ruby
{{ cms:helper render_api_namespace_resource 'movies', { snippet: 'movies-staging' } }}
```
https://user-images.githubusercontent.com/73725297/204227285-863ccc4a-536b-425d-865c-959e1f4e10bd.mp4

[feature] associate multiple snippets with API #show and #index

---

app/helpers/content_helper.rb
test/helpers/content_helper_test.rb

Addresses #1122
The `snippet` option needs to be provided in order to render a snippet other than the default index or show snippet. The default snippet will be rendered if `snippet` option is not provided.
An alternative snippet `movies-staging` for `movies` API namespace can be rendered in the following way:
```ruby
{{ cms:helper render_api_namespace_resource_index 'movies', { snippet: 'movies-staging' } }}
```
An alternative snippet `movies-staging-show` for `movies` API namespace can be rendered in the following way:
```ruby
{{ cms:helper render_api_namespace_resource 'movies', { snippet: 'movies-staging' } }}
```
https://user-images.githubusercontent.com/73725297/204227285-863ccc4a-536b-425d-865c-959e1f4e10bd.mp4
Co-authored-by: Mushfiq Rahman <mushfiqurrahman78@yahoo.com>

[feature] associate multiple snippets with API #show and #index (#1262)

---

app/models/api_namespace.rb
app/views/comfy/admin/api_namespaces/_search_filters.haml
test/controllers/admin/comfy/api_namespaces_controller_test.rb

Addresses: https://github.com/restarone/violet_rails/issues/1225
**Demo**
https://user-images.githubusercontent.com/25191509/201937978-4f162ef3-2b98-4ba1-9112-26e8ae53613e.mov
Co-authored-by: Prashant <25191509+alis-khadka@users.noreply.github.com>

[bug fix] can't search by name in API #index (#1275)

---

.github/workflows/dokku-clean-review-apps.yml

The code changes will delete the review-apps' folder on dokku EC2 instance if its folder still exists while cleaning up all review-apps.
Co-authored-by: Don Restarone <35935196+donrestarone@users.noreply.github.com>

[CI] Job to delete all review apps

---

.github/workflows/dokku-clean-review-apps.yml

The code changes will delete the review-apps' folder on dokku EC2 instance if its folder still exists while cleaning up all review-apps.
Co-authored-by: Don Restarone <35935196+donrestarone@users.noreply.github.com>

[CI] Job to delete all review apps (#1279)

---

app/helpers/content_helper.rb
test/helpers/content_helper_test.rb

Addresses: https://github.com/restarone/violet_rails/issues/1278
**Demo**
https://user-images.githubusercontent.com/25191509/207099710-6da8a326-1109-4f10-9182-0b06c71c6393.mov

[bug fix] don't raise error when API Resource ID is bad

---

client/package-lock.json
yarn.lock

* Bump express from 4.17.1 to 4.18.2 (#1286)
Bumps [express](https://github.com/expressjs/express) from 4.17.1 to 4.18.2.
- [Release notes](https://github.com/expressjs/express/releases)
- [Changelog](https://github.com/expressjs/express/blob/master/History.md)
- [Commits](https://github.com/expressjs/express/compare/4.17.1...4.18.2)
---
updated-dependencies:
- dependency-name: express dependency-type: indirect ...
Signed-off-by: dependabot[bot] <support@github.com>
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
* Bump qs from 6.5.2 to 6.5.3 (#1285)
Bumps [qs](https://github.com/ljharb/qs) from 6.5.2 to 6.5.3.
- [Release notes](https://github.com/ljharb/qs/releases)
- …

[dependencies] JS dependency bump December 2022

---

test/fixtures/api_actions.yml
test/fixtures/api_namespaces.yml
test/fixtures/api_resources.yml
test/plugins/timesheet_request_plugin_test.rb

existing code in https://team.restarone.solutions/api_namespaces/4/api_actions/action_workflow
Co-authored-by: Aashutosh Poudel <aashutoshpoudyal@gmail.com>

[plugin] timesheet tracker (#1313)

---

.github/workflows/deploy.yml

Addresses: https://github.com/restarone/violet_rails/issues/1312

[CI/CD] stop using set-output in cap deploy

---

app/helpers/api_forms_helper.rb
app/views/comfy/admin/api_namespaces/_form.html.haml
test/controllers/admin/comfy/api_resources_controller_test.rb

Addresses: https://github.com/restarone/violet_rails/issues/1111
If has_form is unchecked, 
then the form is not rendered

[bug fix] non renderable API Namespace unable to create Resources

---

app/models/api_namespace.rb
test/models/api_namespace_test.rb

Addresses: https://github.com/restarone/violet_rails/issues/1321
**DEMO**
https://user-images.githubusercontent.com/25191509/216809971-c0b7d411-9b0f-4479-a4ed-263f07cb4429.mov

[Bug Fix]: CMS association not detected when API form is rendered

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/comfy/admin/users_controller.rb
app/views/comfy/admin/users/_form.haml
config/environments/development.rb
config/initializers/rack_profiler.rb
db/migrate/20230310222034_add_show_profiler_to_users.rb
db/schema.rb

When enabled, shows profiling information to admin users
Ensure user has `show profiler` permission
Append `?pp=help` to access the profiling help page
Use instrumentation to track down performance bottlenecks and improve app performance

[feature] enable profiling in production

---

app/controllers/comfy/admin/api_namespaces_controller.rb
app/helpers/api_namespaces_helper.rb
app/models/concerns/jsonb_search/query_builder.rb
app/views/comfy/admin/api_namespaces/show.html.haml
test/controllers/admin/comfy/api_namespaces_controller_test.rb
test/controllers/api/resource_controller_test.rb
test/models/concerns/jsonb_search/query_builder_test.rb

Addresses: https://github.com/restarone/violet_rails/issues/1374
**DEMO**
https://user-images.githubusercontent.com/25191509/214291392-23e3c962-31ce-4df3-b3fa-1a2565c978be.mov
For http-request to search by `KEYWORDS`, we would need to pass `option:  KEYWORDS` as key-value pair for the attributes we want to search by in `properties` payload.
In the clip below, we are filtering `cars` by searching in its attributes, namely: `make`, `model` and `type` with `KEYWORDS` option.
https://user-images.githubusercontent.com/25191509/224547568-37ff1e9c-51e0-4212-bfa4-dd123c9857ac.mov
Payload Example:
```
properties: {"make":{"value":"kia tesla","option":"KEYWORDS"},"model":{"value":"kia tesla","option":"KEYWORDS"},"type":{"value":"kia tesla","option":"KEYWORDS"}},
match: ANY
```

[feature] Ability to query API resources with KEYWORDS

---

app/controllers/application_controller.rb
app/controllers/comfy/admin/v2/dashboard_controller.rb
app/helpers/dashboard_helper.rb
app/models/ahoy/event.rb
app/views/comfy/admin/v2/dashboard/_events.html.haml
app/views/comfy/admin/v2/dashboard/dashboard.html.haml
config/initializers/strong_migrations.rb
db/migrate/20230321055733_add_index_to_ahoy_events_name_and_time.rb
db/schema.rb
db/seeds.rb
db/violet_seeds/violet.rb
test/controllers/admin/comfy/v2/dashboard_controller_test.rb
test/helpers/dashboard_helper_test.rb
test/integration/mini_profiler_test.rb
test/models/ahoy/event_test.rb

Addresses: https://github.com/restarone/violet_rails/issues/1399 and https://github.com/restarone/violet_rails/issues/1452
When analysis going back 1 year is shown, there is a noticeable performance improvement:
When a 1 year analysis is shown, less memory and objects are allocated and retained: 
on a per request basis, we observe that the garbage collector runs before the request is served. Indicating that used memory has been drained and freed to be used for other requests.

[fix] optimize analytics V2 further + lockdown profiler 

---

app/assets/stylesheets/api_namespaces.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/comfy/admin/cms/custom.sass
app/controllers/comfy/admin/api_namespaces_controller.rb
app/javascript/controllers/api_namespaces_controller.js
app/javascript/controllers/api_resources_controller.js
app/javascript/controllers/list_view_controller.js
app/views/comfy/admin/api_namespaces/_table.html.haml
app/views/comfy/admin/api_namespaces/api_resources/_index.html.haml
app/views/comfy/admin/api_namespaces/api_resources/_table.html.haml
app/views/comfy/admin/api_namespaces/index.html.haml
test/controllers/admin/comfy/api_namespaces_controller_test.rb

Addresses: #1503 
When you had a big API Namespace it would break the view: 
https://user-images.githubusercontent.com/73725297/230971387-635f4744-4acb-46f7-a056-12a1541a4351.mp4

[feature] improved API namespaces list view

---

app/assets/stylesheets/api_namespaces.scss
app/controllers/comfy/admin/api_namespaces_controller.rb
app/controllers/comfy/admin/api_resources_controller.rb
app/models/api_namespace.rb
app/models/api_resource.rb
app/models/external_api_client.rb
app/views/comfy/admin/api_namespaces/_association_form.html.haml
app/views/comfy/admin/api_namespaces/_associations.html.haml
app/views/comfy/admin/api_namespaces/_form.html.haml
app/views/comfy/admin/api_namespaces/api_resources/_table.html.haml
app/views/comfy/admin/api_namespaces/show.html.haml
app/views/comfy/admin/api_resources/show.html.haml
config/database.yml
db/migrate/20230516012035_add_associations_to_api_namespace.rb
db/schema.rb
test/controllers/admin/comfy/api_namespaces_controller_test.rb
test/models/api_namespace_test.rb
test/models/api_resource_test.rb

The API Namespace Association feature allows you to define associations between different API namespaces in your application. It enables you to establish relationships such as has_one, has_many, and belongs_to between API namespaces. This feature enhances the flexibility and convenience of working with API resources by automatically generating dynamic methods for accessing associated resources.
Associations can be defined while creating or editing API namespaces
https://github.com/restarone/violet_rails/assets/50227291/4e0a6736-846c-4ac1-88bb-165db5e0df98
OR using rails console
`ApiNamespace.friendly.find('shops').update(associations: [{type: 'has_many', namespace: 'products'}])`
NOTE: Associated namespace (products) must exist before creating an association.
After assigning associations …

API namespace associations

---

README.md
app/assets/stylesheets/api_namespaces.scss
app/controllers/comfy/admin/api_namespaces_controller.rb
app/controllers/comfy/admin/api_resources_controller.rb
app/models/api_namespace.rb
app/models/api_resource.rb
app/models/external_api_client.rb
app/views/comfy/admin/api_namespaces/_association_form.html.haml
app/views/comfy/admin/api_namespaces/_associations.html.haml
app/views/comfy/admin/api_namespaces/_form.html.haml
app/views/comfy/admin/api_namespaces/api_resources/_table.html.haml
app/views/comfy/admin/api_namespaces/show.html.haml
app/views/comfy/admin/api_resources/show.html.haml
db/migrate/20230516012035_add_associations_to_api_namespace.rb
db/schema.rb
test/controllers/admin/comfy/api_namespaces_controller_test.rb
test/models/api_namespace_test.rb
test/models/api_resource_test.rb

The API Namespace Association feature allows you to define associations between different API namespaces in your application. It enables you to establish relationships such as has_one, has_many, and belongs_to between API namespaces. This feature enhances the flexibility and convenience of working with API resources by automatically generating dynamic methods for accessing associated resources.
Associations can be defined while creating or editing API namespaces
https://github.com/restarone/violet_rails/assets/50227291/4e0a6736-846c-4ac1-88bb-165db5e0df98
OR using rails console
`ApiNamespace.friendly.find('shops').update(associations: [{type: 'has_many', namespace: 'products'}])`
NOTE: Associated namespace (products) must exist before creating an association.
After assigning associations …

[feature] API Namespace Associations, update README

---

app/controllers/mailbox/mailbox_controller.rb
app/controllers/mailbox/message_threads_controller.rb
app/helpers/content_helper.rb
app/mailboxes/e_mailbox.rb
app/views/mailbox/mailbox/show.html.haml
app/views/mailbox/message_threads/_index.haml
db/seeds.rb
test/controllers/mailbox/mailbox_controller_test.rb
test/controllers/mailbox/message_threads_controller_test.rb
test/mailboxes/e_mailbox_test.rb

The problem: 
email preview showing full email message in email threads list view:
fixes,
- rendering overflow in email list view - list items are now a fixed size
- sorting when email threads are updated with new messages - threads with unread messages, or new thread show up at the top 
https://github.com/restarone/violet_rails/assets/35935196/438b3148-708c-4473-b1cb-436685d7e14b

Email bug fixes august 2023 (#1581)

---

.gitignore
app/controllers/comfy/admin/api_namespaces_controller.rb
app/models/api_namespace.rb
app/views/comfy/admin/api_namespaces/_form.html.haml
test/controllers/admin/comfy/api_namespaces_controller_test.rb
test/controllers/admin/comfy/api_resources_controller_test.rb
test/plugin_fixtures/sync_attribute_to_api_namespace.yml

addresses: https://github.com/restarone/violet_rails/issues/1588
Upon API Namespace creation, an index page (for rendering a list of entities) and show page (for rendering a specific entity by ID) are generated along with Snippets for rendering list and show views. For convenience, a breadcrumb navigation bar and creation form are included in the generated pages.

[feature] scaffold renderer at API Namespace creation

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/controllers/comfy/admin/calendars_controller.rb
app/controllers/meetings_controller.rb
app/mailboxes/e_mailbox.rb
app/models/meeting.rb
app/views/comfy/admin/calendars/index.html.haml
app/views/comfy/admin/cms/partials/_navigation_inner.haml
app/views/meetings/_form.html.haml
app/views/meetings/_meeting.json.jbuilder
app/views/meetings/edit.html.haml
app/views/meetings/index.html.haml
app/views/meetings/index.json.jbuilder
app/views/meetings/new.html.haml
app/views/meetings/show.html.haml
app/views/meetings/show.json.jbuilder
app/views/simple_calendar/_calendar.html.erb
app/views/simple_calendar/_month_calendar.html.erb
app/views/simple_calendar/_week_calendar.html.erb
config/routes.rb
db/migrate/20230913160600_create_meetings.rb
db/schema.rb
test/controllers/meetings_controller_test.rb
test/fixtures/files/email_with_calendar_invite.eml
test/fixtures/meetings.yml
test/mailboxes/e_mailbox_test.rb

addresses: https://github.com/restarone/violet_rails/issues/1597
This release adds the ability for Violet to handle your calendar. Incoming emails with .ics attachments will automatically be added to your calendar as meetings.
todo: 
1. include .vcs file for outlook
2. add validations to meeting model
further reading: 
1. icalendar syncing events: https://joshfrankel.me/blog/lemme-pencil-you-in-using-icalendar-and-rails-to-sync-calendar-events/
2. all the options: https://blog.corsego.com/icalendar-ruby
3. publish? https://stackoverflow.com/questions/55927263/what-does-icalendar-publish-method-do
4. dealing with email client quirkyness when displaying RSVP buttons: https://stackoverflow.com/questions/66102584/when-i-add-method-request-to-icalendar-gmail-stops-recognizing-as-event

[feature] Calendar and icalendar meetings

---

app/controllers/comfy/admin/cms/pages_controller.rb

print errors when page creation fails

[observability] print errors when page creation fails

---

app/controllers/comfy/admin/web_settings_controller.rb
app/controllers/mailbox/tracking_controller.rb
app/mailers/e_mailer.rb
app/views/comfy/admin/web_settings/_form.haml
app/views/e_mailer/ship.html.erb
app/views/mailbox/message_threads/show.html.haml
config/routes.rb
db/migrate/20241006155850_add_tracking_for_emails.rb
db/schema.rb

* basic implementation for email tracking opt-in

[feature] email tracking opt-in

---

.github/workflows/ruby.yml
docker-compose.yml

adjust image name for docker 2025, where: WARN[0000] /Users/restarone/Documents/violet_rails/docker-compose.yml: the attribute version is obsolete, it will be ignored, please remove it to avoid potential confusion

fix Dockerfile (post-2024) & GHA CI (deprecated actions 2025)

---

.github/workflows/ruby.yml
docker-compose.yml

* adjust image name for docker 2025, where: WARN[0000] /Users/restarone/Documents/violet_rails/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
* fix: This request has been automatically failed because it uses a deprecated version of . Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
---------

fix Dockerfile (post-2024) & GHA CI (deprecated actions 2025) (#1672)
