restarone/violet_rails

app/controllers/users/registrations_controller.rb, test/controllers/users/registrations_controller_test.rb
https://github.com/restarone/violet_rails/issues/78
=> redirect to naked domain for sign up

.gitignore, Capfile, Gemfile, Gemfile.lock, app/controllers/comfy/admin/web_settings_controller.rb, app/controllers/content_controller.rb, app/helpers/subdomain_helper.rb, app/views/comfy/admin/web_settings/edit.haml, app/views/layouts/comfy/blog/application.html.erb, app/views/layouts/forum.html.erb, app/views/layouts/website.html.erb, app/views/shared/_meta_tags.html.erb, config/deploy.rb, config/initializers/comfortable_mexican_sofa.rb, config/sitemap.rb, db/migrate/20210522224212_add_seo_columns_to_subdomain.rb, db/schema.rb
currently, sitemaps run on capistrano deploys only. Need to make sure they run on heroku deployments as well. 
Ill leave this up here till the SEO starts getting better. Im not entirely sure if the sitemap generator is working as expected.
=> Seo strategy

app/controllers/comfy/admin/web_settings_controller.rb, app/models/subdomain.rb, app/views/comfy/admin/web_settings/_form.haml, config/schedule.rb, db/migrate/20210815214536_add_ahoy_visit_cleaning_frequency_to_subdomain.rb, db/schema.rb, lib/tasks/maintenance.rake
https://github.com/restarone/violet_rails/issues/210
=> Configurable ahoy visit purging

app/controllers/search_controller.rb, app/helpers/search_helper.rb, app/views/comfy/admin/cms/partials/_page_form_inner.haml, app/views/comfy/helpers/search/_render.haml, config/routes.rb, db/migrate/20210521152836_add_private_cms_pages.rb, db/migrate/20210823235033_add_preview_to_cms_pages.rb, db/schema.rb, test/controllers/search_controller_test.rb
ability to search for page content over AJAX
docs: https://github.com/restarone/violet_rails/wiki/custom-web-development-guide#searching-website-pages
=> query pages via endpoint/form

config/deploy.rb
trying to fix: https://github.com/restarone/violet_rails/issues/358
=> RC: add explicit clean up

Gemfile, Gemfile.lock, db/seeds.rb
fixes bootsnap load error in docker dev + adds apex domain name bootstrapping to seeds file
=> rc: fix bootsnap load error in docker dev + adds apex domain name bootstrapping to seeds file

.github/workflows/ruby.yml, app/controllers/comfy/admin/web_settings_controller.rb, app/controllers/ember_cli/ember_controller.rb, app/views/comfy/admin/web_settings/_form.haml, db/migrate/20220416155149_add_ember_render_control_to_subdomain.rb, db/schema.rb, test/integration/ember/ember_js_renderer_test.rb
https://github.com/restarone/violet_rails/issues/373
=> release request: ability to toggle the ember app + test

.github/workflows/ruby.yml, app/controllers/comfy/admin/web_settings_controller.rb, app/controllers/ember_cli/ember_controller.rb, app/views/comfy/admin/web_settings/_form.haml, db/migrate/20220416155149_add_ember_render_control_to_subdomain.rb, db/schema.rb, test/integration/ember/ember_js_renderer_test.rb
* ability to toggle the ember app + test
* add ember build routine to CI
acceptance criteria: after release `/app` path should be blocked for everyone by default
=> release request: ability to toggle the ember app + test (#377)

Gemfile, Gemfile.lock, app/controllers/comfy/admin/web_settings_controller.rb, app/controllers/graphql_controller.rb, app/graphql/mutations/base_mutation.rb, app/graphql/r_solutions_schema.rb, app/graphql/types/api_namespace_type.rb, app/graphql/types/api_resource_type.rb, app/graphql/types/base_argument.rb, app/graphql/types/base_connection.rb, app/graphql/types/base_edge.rb, app/graphql/types/base_enum.rb, app/graphql/types/base_field.rb, app/graphql/types/base_input_object.rb, app/graphql/types/base_interface.rb, app/graphql/types/base_object.rb, app/graphql/types/base_scalar.rb, app/graphql/types/base_union.rb, app/graphql/types/mutation_type.rb, app/graphql/types/node_type.rb, app/graphql/types/query_type.rb, app/helpers/api_namespaces_helper.rb, app/views/admin/shared/_navbar.haml, app/views/comfy/admin/api_namespaces/show.html.haml, app/views/comfy/admin/web_settings/_form.haml, config/routes.rb, db/migrate/20220416213659_add_graphql_to_subdomain.rb, db/schema.rb, test/controllers/graphql_controller_test.rb
* install graphql
* remove graphiql UI gem from dev group because we probably willhave the need to debug in prod
* basic implementation for querying apinamespaces/resources
* show graphql UI in sysadmin
* ability to sort, limit and offset publically available API namespaces
* basic test graphql support
* add tests + patch issues
* add support for searching by slug + generate docs
=> [Experimental] Add graphql support (#386)

Gemfile.lock
fix error: 
``` txt
I, [2022-04-17T04:33:25.855240 #69870]  INFO -- : [f3a94326-ed34-47be-a5f6-13ac203f6ff8] Started GET "/forum/threads/discover-nikean-org" for 76.64.37.224 at 2022-04-17 04:33:25 +0000
D, [2022-04-17T04:33:25.857795 #69870] DEBUG -- : [f3a94326-ed34-47be-a5f6-13ac203f6ff8]   Subdomain Load (0.9ms)  SELECT "public"."subdomains".* FROM "public"."subdomains"
I, [2022-04-17T04:33:25.861211 #69870]  INFO -- : [f3a94326-ed34-47be-a5f6-13ac203f6ff8] Processing by SimpleDiscussion::ForumThreadsController#show as HTML
I, [2022-04-17T04:33:25.861280 #69870]  INFO -- : [f3a94326-ed34-47be-a5f6-13ac203f6ff8]   Parameters: {"id"=>"discover-nikean-org"}
D, [2022-04-17T04:33:25.863243 #69870] DEBUG -- : [f3a94326-ed34-47be-a5f6-13ac203f6ff8]   Subdomain Load (1.0ms)  SELECT …
```
=> fix loofah x2 after testing in staging (#403)

app/controllers/comfy/admin/api_clients_controller.rb, app/controllers/comfy/admin/external_api_clients_controller.rb, app/models/api_namespace.rb, app/models/api_resource.rb, app/models/external_api_client.rb, app/sidekiq/external_api_client_job.rb, app/views/comfy/admin/api_namespaces/_init_editor.haml, app/views/comfy/admin/api_namespaces/show.html.haml, app/views/comfy/admin/external_api_clients/_form.html.haml, app/views/comfy/admin/external_api_clients/edit.html.haml, app/views/comfy/admin/external_api_clients/index.html.haml, app/views/comfy/admin/external_api_clients/new.html.haml, app/views/comfy/admin/external_api_clients/show.html.haml, config/routes.rb, db/migrate/20220315185029_create_external_api_clients.rb, db/schema.rb, test/controllers/admin/comfy/api_clients_controller_test.rb, test/controllers/admin/comfy/external_api_clients_controller_test.rb, test/fixtures/external_api_clients.yml, test/models/external_api_client_test.rb, test/sidekiq/external_api_client_job_test.rb, test/test_helper.rb
external API client allows you to prototype and build integrations: 
1. define a custom class that describes the external interface 
2. use metadata to track connection details (URL's, authentication secrets etc)
3. use state_metadata to track runner state
4. ETL pattern (save to API namespace / create API resources)
5. monitor task for class level errors
6. worker level errors are tracked by sidekiq
backed by sidekiq: 
dynamic model definition: 
to do: add a better editor for editing the model
=> [Release Request] External api client (#363)

Gemfile, app/controllers/admin/web_console_controller.rb, app/controllers/comfy/admin/web_settings_controller.rb, app/views/admin/shared/_navbar.haml, app/views/admin/subdomain_requests/index.haml, app/views/admin/web_console/index.haml, app/views/comfy/admin/web_settings/_form.haml, config/application.rb, config/environments/development.rb, config/initializers/web_console.rb, config/routes.rb, db/migrate/20220417193128_add_webconsole_to_subdomain.rb, db/schema.rb, test/controllers/admin/web_console_controller_test.rb
web console support: 
1. run arbitrary ruby (evil) 
2. restricted to domain owner/sysadmins (only executable on the public schema of the domain apex)
=> [release request] Add webconsole (#410)

app/mailers/simple_discussion/user_mailer.rb, test/controllers/simple_discussion/forum_threads_controller_test.rb
https://github.com/restarone/violet_rails/issues/413
=> [Bug fix] set forum notification email origin explicitly

app/controllers/comfy/admin/users_controller.rb, app/controllers/comfy/admin/web_settings_controller.rb, app/controllers/subdomains/base_controller.rb, app/views/comfy/admin/users/edit.haml, db/migrate/20220420034907_add_web_settings_access_to_users.rb, db/schema.rb, test/controllers/admin/comfy/web_settings_controller_test.rb
add new permission for managing subdomain settings
https://github.com/restarone/violet_rails/issues/220
=> [feature] add new permission for managing subdomain settings + test

app/controllers/comfy/admin/users_controller.rb, app/controllers/comfy/admin/web_settings_controller.rb, app/controllers/subdomains/base_controller.rb, app/views/comfy/admin/users/edit.haml, db/migrate/20220420034907_add_web_settings_access_to_users.rb, db/schema.rb, test/controllers/admin/comfy/web_settings_controller_test.rb
add new permission for managing subdomain settings
https://github.com/restarone/violet_rails/issues/220
=> add new permission for managing subdomain settings  (#425)

app/controllers/users/registrations_controller.rb, app/models/user.rb, app/views/users/registrations/edit.html.erb, db/migrate/20220420133828_add_session_timeout_to_users.rb, db/schema.rb, test/models/user_test.rb
https://github.com/restarone/violet_rails/issues/309
=> [Feature] dynamic session timeout for users (#427)

app/controllers/comfy/admin/web_settings_controller.rb, app/controllers/simple_discussion/forum_posts_controller.rb, app/controllers/simple_discussion/forum_threads_controller.rb, app/mailboxes/e_mailbox.rb, app/models/api_action.rb, app/models/api_namespace.rb, app/services/subdomain_events_service.rb, app/sidekiq/api_resource_spawn_job.rb, app/views/comfy/admin/web_settings/_form.haml, db/migrate/20220420153229_add_plugin_subdomain_events_to_api.rb, db/schema.rb, test/controllers/admin/comfy/api_resources_controller_test.rb, test/controllers/simple_discussion/forum_threads_controller_test.rb, test/fixtures/api_actions.yml, test/fixtures/api_namespaces.yml, test/fixtures/api_resources.yml, test/mailboxes/e_mailbox_test.rb, test/models/api_namespace_test.rb, test/models/subdomain_test.rb
[…write tests that check for object.last unless you know for sure the last object is predictable -- ie; if you created it during the test [run](https://github.com/restarone/violet_rails/issues/430)](https://github.com/restarone/violet_rails/issues/430)
=> WIP [API Plugin] Subdomain Events

app/controllers/application_controller.rb, app/controllers/comfy/admin/users_controller.rb, app/controllers/comfy/admin/web_settings_controller.rb, app/controllers/users/registrations_controller.rb, app/views/comfy/admin/users/_form.haml, app/views/comfy/admin/users/edit.haml, app/views/comfy/admin/web_settings/_form.haml, config/initializers/comfortable_mexican_sofa.rb, db/migrate/20220421233500_add_has_access_to_admin_to_users.rb, db/migrate/20220422003307_add_redirects_to_subdomain.rb, db/schema.rb, test/controllers/admin/comfy/cms/content_controller_test.rb, test/controllers/admin/comfy/layouts_controller_test.rb, test/controllers/admin/comfy/pages_controller_test.rb, test/controllers/mailbox/base_controller_test.rb, test/controllers/users/registrations_controller_test.rb, test/controllers/users/sessions_controller_test.rb, test/fixtures/users.yml
https://github.com/restarone/violet_rails/issues/436
=> [Feature] access rules for /admin + custom  redirection rules

app/views/active_storage/blobs/_blob.html.erb, test/mailers/simple_discussion/user_mailer_test.rb
[bug fix] forum email notification not sent when image file is attached
https://github.com/restarone/violet_rails/issues/422
=> [bug fix] forum email notification not sent when image file is attached

Dockerfile.dev
https://github.com/restarone/violet_rails/issues/402
=> Docker Dev workflow is broken (apple M1)

Dockerfile.dev, db/seeds.rb
[Bug fix] Apple M1 dev workflow fixes + fix seeds.rb
https://github.com/restarone/violet_rails/issues/402
=> [Bug fix] Apple M1 dev workflow fixes + fix seeds.rb

Dockerfile.dev, app/models/user.rb, db/seeds.rb
fix canonical user permissions after subdomain bootstrap
https://github.com/restarone/violet_rails/issues/451
=> [bug fix] fix canonical user permissions after subdomain bootstrap

app/controllers/comfy/admin/external_api_clients_controller.rb, app/models/external_api_client.rb, app/views/comfy/admin/external_api_clients/_form.html.haml, app/views/comfy/admin/external_api_clients/show.html.haml, config/schedule.rb, db/migrate/20220423235433_add_cron_support_to_external_api_client.rb, db/schema.rb, lib/tasks/external_api_client.rake, test/tasks/external_api_client_cron_job_test.rb
* add cron support to external api client
* run job in sidekiq
Co-authored-by: donrestarone <shashikejayatunge@gmail.co>
=> [Feature] Add cron support to external api client (#469)

app/views/active_storage/blobs/_blob.html.erb
https://github.com/restarone/violet_rails/issues/468
=> [bug fix] minor change for forum email notification not sent when image file is attached

app/views/active_storage/blobs/_blob.html.erb
https://github.com/restarone/violet_rails/issues/468
figure: web-view
figure: email-view
figure: web-view
figure: email-view
=> [bug fix] Images not rendering for attached images in ForumPosts

app/services/api_namespace/plugin/v1/subdomain_events_service.rb, app/sidekiq/api_resource_spawn_job.rb, config/initializers/sidekiq.rb
fix sidekiq serialization warning
=> fix sidekiq serialization warning

app/controllers/comfy/admin/external_api_clients_controller.rb, app/models/external_api_client.rb, app/services/api_namespace/plugin/v1/subdomain_events_service.rb, app/sidekiq/api_resource_spawn_job.rb, app/sidekiq/external_api_client_job.rb, config/initializers/sidekiq.rb, lib/tasks/external_api_client.rake, test/models/external_api_client_test.rb
fix sidekiq serialization warning (#485)
fix sidekiq usage in external api client system
address issues raised in: https://github.com/restarone/violet_rails/issues/478
=> fix sidekiq serialization warning (#485)

config/schedule.rb, lib/tasks/api_action.rake
as part of https://github.com/restarone/violet_rails/issues/478 
remove expensive cron job (#489)
=> remove expensive cron job (#489)

app/views/comfy/admin/api_namespaces/show.html.haml
=> Fix UI in API Resource show (#505)

app/controllers/comfy/admin/api_resources_controller.rb, app/controllers/resource_controller.rb, app/helpers/api_resources_helper.rb, app/models/api_action.rb, app/models/api_form.rb, app/models/api_namespace.rb, app/models/api_resource.rb, app/models/concerns/jsonb_fields_parsable.rb, app/models/external_api_client.rb, app/views/api_action_mailer/send_email.html.erb, app/views/comfy/admin/api_actions/_form.html.haml, app/views/comfy/admin/api_forms/_form.html.haml, app/views/comfy/admin/api_forms/_render.haml, app/views/comfy/admin/api_namespaces/_editor.haml, app/views/comfy/admin/api_namespaces/_form.html.haml, app/views/comfy/admin/api_namespaces/show.html.haml, app/views/comfy/admin/external_api_clients/_form.html.haml, app/views/comfy/admin/external_api_clients/show.html.haml, db/migrate/20220423142107_convert_json_string_properties_to_json.rb, test/controllers/admin/comfy/api_namespaces_controller_test.rb, test/fixtures/api_actions.yml, test/fixtures/api_namespaces.yml, test/fixtures/api_resources.yml, test/fixtures/external_api_clients.yml, test/models/concerns/json_fields_parsable_test.rb
* chore(): fix db incosistency
* raise validation error if provied value is not valid json
* fix test cases
* test json field parsable
* test json field parsable
* rename spec name
Co-authored-by: Shashike Jayatunge <35935196+donrestarone@users.noreply.github.com>
=> Fix JSONb usage inconsistencies (#500)

app/controllers/comfy/admin/cms/files_controller.rb, app/controllers/comfy/admin/cms/pages_controller.rb, app/controllers/comfy/admin/dashboard_controller.rb, app/controllers/comfy/admin/users_controller.rb, app/controllers/comfy/admin/web_settings_controller.rb, app/controllers/comfy/blog/posts_controller.rb, app/controllers/mailbox/message_threads_controller.rb, app/controllers/simple_discussion/forum_posts_controller.rb, app/controllers/simple_discussion/forum_threads_controller.rb, app/helpers/dashboard_helper.rb, app/models/user.rb, app/views/comfy/admin/dashboard/dashboard.html.haml, app/views/comfy/admin/dashboard/visit.haml, app/views/comfy/admin/users/edit.haml, app/views/comfy/admin/web_settings/_form.haml, config/initializers/comfortable_mexican_sofa.rb, config/routes.rb, db/migrate/20220414025112_add_tracking_toggle_to_subdomains.rb, db/schema.rb, test/controllers/admin/comfy/blog/posts_controller_test.rb, test/controllers/admin/comfy/cms/content_controller_test.rb, test/controllers/admin/comfy/dashboard_controller_test.rb, test/controllers/admin/comfy/pages_controller_test.rb, test/controllers/admin/comfy/users_controller_test.rb, test/controllers/comfy/admin/cms/files_controller_test.rb, test/controllers/mailbox/message_threads_controller_test.rb, test/controllers/simple_discussion/forum_posts_controller_test.rb, test/controllers/simple_discussion/forum_threads_controller_test.rb
* basic setup for tracking
* add tracking to blog post
* feat(): event tracking when users edits file, page, forum-post & another user
* feat(): tracking events when user views forum-thread & email
* feat(): re-design of visit page for showing session details
* feat(): added test cases for tracking enabled controller methods
* feat(): checking if the variable current_visit has session details while tracking events
* feat(): removing duplicate pages_controller_test.rb
* feat(): showing user's visit count in session detail page conditionally
=> [Experimental] Event tracking (#359)

config/initializers/comfortable_mexican_sofa.rb
https://github.com/restarone/violet_rails/issues/531
=> [bug fix] gracefully look for visit/user id

config/environments/production.rb, config/environments/staging.rb
dont report on action controller routing error 
``` txt
An ActionController::RoutingError occurred in content#show:
Page Not Found at: "c"
-------------------------------
Request:
-------------------------------
* URL        : https://3.99.30.108/c
* HTTP Method: GET
* IP address : 180.149.125.170
* Parameters : {"controller"=>"comfy/cms/content", "action"=>"show", "cms_path"=>"c"}
* Timestamp  : 2022-05-07 22:59:34 UTC
* Server : ip-172-31-14-250
* Rails root : /var/www/violet/releases/20220507203205
* Process: 1151700
-------------------------------
Session:
-------------------------------
* session id: [FILTERED]
* data: {}
-------------------------------
Environment:
-------------------------------
* GATEWAY_INTERFACE                                       : CGI/1.2
* HTTP_ACCEPT …
```
=> dont report routing error (#540)

app/assets/stylesheets/flash.scss, app/views/shared/_flash.haml
https://github.com/restarone/violet_rails/issues/455
authored by @alis-khadka
=> [bug fix] - show system flash messages regardless of custom CSS

config/environments/production.rb, config/environments/staging.rb
adds Gzip compression: 
research: 
https://railshero.pw/153/enabling-gzip-compression-in-your-rails-apps/
https://www.rubydoc.info/gems/rack/Rack/Deflater
https://thoughtbot.com/blog/content-compression-with-rack-deflater
=> add middleware

app/controllers/resource_controller.rb, app/models/api_resource.rb, test/models/api_resource_test.rb
@Pralish does this solution look viable for: https://github.com/restarone/violet_rails/pull/558
=> Rc drest patch non renderable value not included in api resource

app/controllers/comfy/admin/web_settings_controller.rb, app/graphql/types/ahoy/event_names_type.rb, app/graphql/types/ahoy/events_type.rb, app/graphql/types/ahoy/visits_type.rb, app/graphql/types/query_type.rb, app/views/comfy/admin/web_settings/_form.haml, db/migrate/20220514215146_add_allow_external_analytics_query_to_subdomain.rb, db/schema.rb, test/controllers/graphql_controller_test.rb
[Feature] allow ahoy visits/events to be queries in GQL (if enabled)
=> [Feature] allow ahoy visits/events to be queries in GQL (if enabled)

app/graphql/types/api_namespace_type.rb, test/controllers/graphql_controller_test.rb
[bug fix] correct scoping in ApiNamespace => children in gql
=> [bug fix] correct scoping in ApiNamespace => children in gql

app/controllers/comfy/admin/cms/files_controller.rb, app/controllers/comfy/admin/dashboard_controller.rb, app/controllers/comfy/admin/users_controller.rb, app/controllers/mailbox/message_threads_controller.rb, app/controllers/simple_discussion/forum_posts_controller.rb, app/controllers/simple_discussion/forum_threads_controller.rb, app/helpers/ahoy_events_helper.rb, app/models/ahoy/event.rb, app/views/comfy/admin/dashboard/_event_type_search_filter.haml, app/views/comfy/admin/dashboard/_events_search_filters.haml, app/views/comfy/admin/dashboard/_pagination.haml, app/views/comfy/admin/dashboard/dashboard.html.haml, app/views/comfy/admin/dashboard/events_detail.haml, app/views/comfy/admin/dashboard/events_list.haml, app/views/comfy/admin/dashboard/visit.haml, config/initializers/comfortable_mexican_sofa.rb, config/routes.rb, test/controllers/admin/comfy/dashboard_controller_test.rb, test/helpers/ahoy_events_helper_test.rb
https://github.com/restarone/violet_rails/issues/518
https://user-images.githubusercontent.com/25191509/169423339-76a21a86-eed8-4999-bce8-28fa48da326f.mp4
1. for each visit (visitor and user): shows events in chronological order by event name
2. for each event name: shows aggregated data
3. passes general regression
=> [Feature] event tracking rev 2 (#596)

Gemfile, Gemfile.lock
rails based maintenance mode with turnout
=> [feature] rails based maintenance mode with turnout

app/views/comfy/admin/cms/partials/_navigation_before.haml
* add same classes to the link as to the image to hide it on mobile #563
=> [bug fix] "Add logo" shifting navbar down on mobile (restarone#563)

app/views/active_storage/blobs/_blob.html.erb
addresses: https://github.com/restarone/violet_rails/issues/600
1. existing forum posts/threads that contain assets (images, files etc) are not broken
2. user is able to update posts/threads with/without assets 
3. functionality works as expected in subdomains and the apex domain
=> [Forum] When a forum post is updated with with image/file, user is presented with error and thumbnail is broken for images.

.github/workflows/brakeman-analysis.yml, .github/workflows/ruby.yml
https://github.com/restarone/violet_rails/issues/630
=> [bug fix] fix CI failure due to missing postgres 12

.github/workflows/heroku-deploy.yml, Gemfile, Gemfile.lock, Procfile, app/models/user.rb, db/schema.rb, package.json
WIP by @alis-khadka 
* [platform] deploy to Heroku as part of CI
[platform] deploy to Heroku as part of CI
* fix warning
* run rails g ember:heroku
* feat(): heroku automated deployment
* feat(): added justlogin in heroku deploy file
* Revert "feat(): added justlogin in heroku deploy file"
This reverts commit 8122048cc02064f16cfe9b47b1a84716eb6124a6.
* chore(): minor change to trigger heroku deploy
* chore(): changing targegting branch
* chore(): revoming branch name on heroku deploy file
* chore(): minor change
* chore(): testing docker deployment
* chore(): testing heroku deployment
* fix(): removing duplicate column api_plugin_events_enabled from subdomains table
* fix(): removing duplicate column trackings_enabled from subdomains table
* feat(): seeding database conditionally
* …
=> [WIP] Automating heroku deployment 

app/controllers/comfy/admin/api_namespaces_controller.rb, app/views/comfy/admin/api_namespaces/export.csv.haml, app/views/comfy/admin/api_namespaces/show.html.haml, config/routes.rb, test/controllers/admin/comfy/api_namespaces_controller_test.rb, test/fixtures/api_namespaces.yml
https://github.com/restarone/violet_rails/issues/321
1. export button is present on all API Namespaces
2. complex API Namespaces can be converted to CSV format
3. API Actions + automations are working as expected
=> [feature] export data from API resource in CSV format

app/controllers/comfy/admin/api_namespaces_controller.rb, app/models/api_namespace.rb, app/views/comfy/admin/api_namespaces/show.html.haml, config/routes.rb, test/controllers/admin/comfy/api_namespaces_controller_test.rb
https://github.com/restarone/violet_rails/issues/622
=> [Violet Rails Core]: Ability to clone api namespace along with its children

.github/workflows/heroku-deploy.yml, Gemfile, Gemfile.lock, Procfile, app/models/user.rb, package.json
addresses: https://github.com/restarone/violet_rails/issues/385
1. EC2 deployments using an older version of Node is still possible 
2. New Node is only used on Heroku
* deploy to heroku
Co-authored-by: donrestarone <shashikejayatunge@gmail.com>
=> [Feature] add automation deploy violet_rails to heroku

app/views/comfy/admin/external_api_clients/_form.html.haml
add a simple code editor to external API Client
=> fix external api client code editor

app/controllers/comfy/admin/dashboard_controller.rb, app/models/ahoy/event.rb, app/views/comfy/admin/dashboard/events_detail.haml, config/routes.rb, test/controllers/admin/comfy/dashboard_controller_test.rb
addresses: https://github.com/restarone/violet_rails/issues/651
1. able delete visits for a given event
2. able to delete event and visits
3. does not delete visits of a event
=> [feature] Ability to delete custom event and visits

app/views/comfy/admin/external_api_clients/_form.html.haml
1. does not mutate/corrupt existing data when the form is rendered and submitted with no changes
2. renders existing data correctly
=> [feature] add code editor to ExternalApiConnection

app/controllers/comfy/admin/api_namespaces_controller.rb, app/mailers/api_action_mailer.rb, app/models/api_action.rb, app/models/concerns/dynamic_attribute.rb, app/models/concerns/safe_executable_validator.rb, app/models/external_api_client.rb, app/views/api_action_mailer/send_email.html.erb, app/views/comfy/admin/api_actions/_form.html.haml, db/migrate/20220609092515_add_email_subject_to_api_actions.rb, db/schema.rb, test/fixtures/external_api_clients.yml, test/models/api_action_test.rb, test/models/concerns/dynamic_attribute_test.rb, test/models/external_api_client_test.rb
https://github.com/restarone/violet_rails/issues/653
https://github.com/restarone/violet_rails/issues/652
=> Dynamic attributes with access to api_resource

app/models/user.rb, app/views/comfy/admin/users/_form.haml, test/controllers/admin/comfy/users_controller_test.rb, test/models/user_test.rb
=> [Bug fix] last admin should not be able to delete themselves

yarn.lock
* chore(deps): bump eventsource from 1.1.0 to 1.1.2 (#695)
Bumps [eventsource](https://github.com/EventSource/eventsource) from 1.1.0 to 1.1.2.
- [Release notes](https://github.com/EventSource/eventsource/releases)
- [Changelog](https://github.com/EventSource/eventsource/blob/master/HISTORY.md)
- [Commits](https://github.com/EventSource/eventsource/compare/v1.1.0...v1.1.2)
---
updated-dependencies:
- dependency-name: eventsource
dependency-type: indirect
...
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
* chore(deps): bump follow-redirects from 1.13.3 to 1.15.1 (#613)
Bumps [follow-redirects](https://github.com/follow-redirects/follow-redirects) from 1.13.3 to 1.15.1.
- [Release …
=> Js deps upgrade jun 10 2022 (#722)

app/views/comfy/admin/api_forms/_render.haml
https://github.com/restarone/violet_rails/pull/709
=> Proper message if no recaptcha keys set

.github/workflows/heroku-deploy.yml, .github/workflows/ruby.yml
Addresses https://github.com/restarone/violet_rails/issues/640
=> [Violet Rails Core] CI action to verify schema.rb integrity

.github/workflows/ruby.yml, package.json
* chore(): changing heroku target temporarily
* chore(): printing npm version
* chore(): updating ruby yaml file
* chore(): using node 10 & 14 while building project in github action
* chore(): using node 10 & 14 while building project in github action
* chore(): updating node version in package.json
* chore(): setting node version to 10.x for testing
* Revert "chore(): setting node version to 10.x for testing"
This reverts commit 173ca7fecd45b3671aed4cf451dfb71a86b7459b.
* Revert "chore(): changing heroku target temporarily"
This reverts commit e040a0f29ac799652e47a8ba996ce0cc9516d07b.
* chore(): removing unwanted changes
* chore(): set required npm version
* chore(): temporary changes for heroku yaml
* chore(): syntax correction
* chore(): typo correction
* chore(): reverting specifying …
=> [feature branch]: Support for node 10 and 14 (#730)

.github/workflows/ruby.yml, package.json, test/models/subdomain_test.rb
https://github.com/restarone/violet_rails/pull/740
https://github.com/restarone/violet_rails/pull/733
https://github.com/restarone/violet_rails/pull/735
=> [Feature] Support for node 10 and 14 + added test for verifying subdomain can be created + CI action to verify schema.rb integrity

.github/workflows/ruby.yml, package.json, test/models/subdomain_test.rb
addresses: 
https://github.com/restarone/violet_rails/issues/660
https://github.com/restarone/violet_rails/issues/640
=> [CI] action to verify schema.rb integrity, [CI] Support for node 10 and 14 builds

app/views/simple_discussion/forum_threads/_forum_thread.html.erb, test/controllers/simple_discussion/forum_threads_controller_test.rb
Addresses https://github.com/restarone/violet_rails/issues/721
=> [Forum]: Show latest post in threads index

app/views/simple_discussion/forum_threads/_forum_thread.html.erb, test/controllers/simple_discussion/forum_threads_controller_test.rb
addresses: https://github.com/restarone/violet_rails/issues/721
* feat(): showing the latest post in thread preview of threads#index
* feat(): added test cases
this is on its way to Heroku for testing @alis-khadka !
=> [feature] forum - show latest post in threads index

app/views/simple_discussion/forum_threads/_forum_thread.html.erb, test/controllers/simple_discussion/forum_threads_controller_test.rb
addresses: https://github.com/restarone/violet_rails/issues/721
* feat(): showing the latest post in thread preview of threads#index
* feat(): added test cases
=> [feature] forum - show latest post in threads index (#755)

test/controllers/admin/comfy/external_api_clients_controller_test.rb
Addressed https://github.com/restarone/violet_rails/issues/694
=> [Violet Rails Core]: add tests for ExternalApiClientsController

app/models/subdomain.rb, lib/tasks/api_action.rake, lib/tasks/external_api_client.rake, lib/tasks/maintenance.rake, lib/tasks/report.rake
=> fix(): include public subdomain when running rake tasks

app/models/subdomain.rb, lib/tasks/api_action.rake, lib/tasks/external_api_client.rake, lib/tasks/maintenance.rake, lib/tasks/report.rake
=> fix data discovery issue in rake tasks (public schema is not accessed) 

config/environments/production.rb, config/environments/staging.rb
addresses: https://github.com/restarone/violet_rails/issues/688
=> dont fallback on asset pipeline

config/environments/production.rb, config/environments/staging.rb
addresses: https://github.com/restarone/violet_rails/issues/688
Co-authored-by: donrestarone <shashikejayatunge@gmail.com>
=> [feature] dont fallback on asset pipeline

app/views/layouts/devise.html.haml
resolves: https://github.com/restarone/violet_rails/issues/774
=> include file extension in Violet Rails logo to prevent asset compilation error

Gemfile, Gemfile.lock, app/javascript/packs/application.js, app/views/comfy/blog/posts/show.html.haml, app/views/layouts/admin.html.haml, app/views/layouts/application.html.erb, app/views/layouts/comfy/admin/cms.html.haml, app/views/layouts/comfy/blog/application.html.erb, app/views/layouts/devise.html.haml, app/views/layouts/forum.html.erb, app/views/layouts/subdomains.html.erb, app/views/layouts/website.html.erb, package.json, yarn.lock
resolves: https://github.com/restarone/violet_rails/issues/105
=> [feature] turbo support in CMS / Forum

config/initializers/devise.rb, test/controllers/users/passwords_controller_test.rb
https://github.com/restarone/violet_rails/issues/783
=> Password Reset Bug

config/initializers/devise.rb, test/controllers/users/passwords_controller_test.rb
resolves: https://github.com/restarone/violet_rails/issues/783
=> fix broken password reset

config/initializers/devise.rb, test/controllers/users/passwords_controller_test.rb
resolves: https://github.com/restarone/violet_rails/issues/783
=> [bug fix] fix broken password reset

app/controllers/mailbox/mailbox_controller.rb, app/models/message.rb, app/views/mailbox/mailbox/_pagination.haml, app/views/mailbox/mailbox/_search_filters.haml, app/views/mailbox/mailbox/show.haml, test/controllers/mailbox/mailbox_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/777
=> [Violet Rails Core] add pagination + search to email threads/index

app/views/comfy/admin/cms/partials/_navigation_before.haml, app/views/comfy/admin/cms/partials/_navigation_inner.haml, test/controllers/admin/comfy/users_controller_test.rb
resolves: https://github.com/restarone/violet_rails/issues/384
* remove buttons when feature is disable
* added negative cases
* updated the test units of the features
=> [feature] when feature is un-enabled remove buttons related to it (#764)

app/controllers/comfy/admin/api_namespaces_controller.rb, app/models/api_namespace.rb, app/views/comfy/admin/api_namespaces/new.html.haml, app/views/comfy/admin/api_namespaces/show.html.haml, config/routes.rb, test/controllers/admin/comfy/api_namespaces_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/679
https://user-images.githubusercontent.com/25191509/175818688-42dc5179-dce9-4b22-a657-888ead6b3490.mp4
=> [feature] export/import API Namespace with/without children in JSON format

README.md
* add status badges
* Update README.md
* change order
=> add status badges (#824)

.github/workflows/heroku-deploy.yml, .github/workflows/ruby.yml
Addresses: https://github.com/restarone/violet_rails/issues/815
=> [CI] Save code coverage as artifact

app/views/comfy/admin/api_namespaces/_form.html.haml, app/views/comfy/admin/api_namespaces/new.html.haml
https://github.com/restarone/violet_rails/pull/821#issuecomment-1167285746
=> Export/Import API Namespace:  UI responsiveness & typo correction

app/controllers/comfy/admin/api_namespaces_controller.rb, app/models/non_primitive_property.rb, app/views/comfy/admin/api_forms/_render.haml, app/views/comfy/admin/api_namespaces/_form.html.haml, app/views/comfy/admin/non_primitive_properties/_nested_form.haml, db/migrate/20220628050113_add_allow_attachments_to_non_primitive_properties.rb, db/migrate/20220628050113_add_disable_file_attachment_to_non_primitive_properties.rb, db/schema.rb, test/models/non_primitive_property_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/661
https://user-images.githubusercontent.com/35935196/176429682-a19cc7b7-f692-4f18-8bc9-7f95947fc9b2.mp4
Unchecked checkbox not passing false to params:
It took me some time to figure this out. In the end, I followed these reference for the workaround;
https://github.com/rails/rails/issues/5937
https://stackoverflow.com/questions/20379311/how-to-get-blank-checkboxes-to-pass-as-false-to-params/20380051#20380051
=> [Violet Rails Core] ability to toggle trix editor attachments

app/controllers/comfy/admin/api_namespaces_controller.rb, app/models/non_primitive_property.rb, app/views/comfy/admin/api_forms/_render.haml, app/views/comfy/admin/api_namespaces/_form.html.haml, app/views/comfy/admin/non_primitive_properties/_nested_form.haml, db/migrate/20220628050113_add_allow_attachments_to_non_primitive_properties.rb, db/schema.rb, test/models/non_primitive_property_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/661
https://user-images.githubusercontent.com/35935196/176429682-a19cc7b7-f692-4f18-8bc9-7f95947fc9b2.mp4
Unchecked checkbox not passing false to params:
It took me some time to figure this out. In the end, I followed these reference for the workaround;
https://github.com/rails/rails/issues/5937
https://stackoverflow.com/questions/20379311/how-to-get-blank-checkboxes-to-pass-as-false-to-params/20380051#20380051
=> [feature] ability to toggle trix editor attachments

config/initializers/active_support.rb
Reference: https://github.com/rails/rails/issues/37672
Addresses: https://github.com/restarone/violet_rails/pull/852
=> Fix for active support error in production

app/mailers/api_action_mailer.rb
target: https://github.com/restarone/violet_rails/pull/866 after CI passes
=> Fixup rc drest

app/views/comfy/admin/api_actions/_form.html.haml
=> Fix textarea overflow in send_email API action workflow

app/controllers/comfy/admin/api_namespaces_controller.rb, app/controllers/concerns/api_actionable.rb, app/controllers/resource_controller.rb, app/models/api_action.rb, app/models/concerns/dynamic_attribute.rb, app/views/comfy/admin/api_actions/_form.html.haml, app/views/comfy/admin/api_actions/show.html.haml, db/migrate/20220707090412_add_redirect_type_to_api_actions.rb, db/schema.rb, test/controllers/resource_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/873
https://user-images.githubusercontent.com/35935196/178011977-82aab515-87b5-49a3-8591-f8ba3535d9eb.mp4
=> [Violet Rails Core] Allow dynamic segment in api redirect action

app/controllers/comfy/admin/web_settings_controller.rb, app/mailboxes/e_mailbox.rb, app/mailers/e_mailer.rb, app/models/subdomain.rb, app/views/comfy/admin/cms/partials/_navigation_inner.haml, app/views/comfy/admin/users/index.html.haml, app/views/comfy/admin/web_settings/_form.haml, app/views/e_mailer/ship.html.erb, config/locales/views/comfy/web_settings/en.yml, db/migrate/20220709172402_add_email_name_and_signature_to_subdomains.rb, db/schema.rb, test/controllers/admin/comfy/users_controller_test.rb, test/fixtures/files/email_with_multiple_recipients.eml, test/mailboxes/e_mailbox_test.rb
resolves: https://github.com/restarone/violet_rails/issues/767
=> [feature] ability to have an email signature + name in email

Gemfile, Gemfile.lock, config/initializers/sidekiq.rb, config/sidekiq.yml
resolves: https://github.com/restarone/violet_rails/issues/904 & https://github.com/restarone/violet_rails/issues/536
1. Sending / receiving emails :heavy_check_mark: 
2. Ahoy geocode / analytics :heavy_check_mark: 
3. file uploads :heavy_check_mark: 
4. file previews :heavy_check_mark: 
5. forum
6. API forms (file upload, rich text) :heavy_check_mark: 
7. ruby automation :heavy_check_mark: 
So be sure to drain all jobs BEFORE deploying this to production
tail the logs for sidekiq: 
``` bash
journalctl -u sidekiq.service -f
```
=> namespace sidekiq + add queues 

test/fixtures/api_namespaces.yml, test/fixtures/api_resources.yml, test/fixtures/external_api_clients.yml, test/plugins/mailchimp_plugin_test.rb
https://gist.github.com/restarone-solutions/5ac432cd98b1015b658c914399d2e44c
update documentation: https://github.com/restarone/violet_rails/issues/720
=> add tests for sync to mailchimp plugin

test/fixtures/api_namespaces.yml, test/fixtures/api_resources.yml, test/fixtures/external_api_clients.yml, test/plugins/mailchimp_plugin_test.rb
Add test for mailchimp sync v2: https://github.com/restarone/violet_rails/issues/720#issuecomment-1183585540
=> test mailchimp plugin (#893) (#914)

bin/rails, ci_env.cfg, run_tests.sh, test/test_helper.rb
resolves: https://github.com/restarone/violet_rails/issues/830
=> [bug fix] test coverage of models reports 0%

ci_env.cfg, run_tests.sh, test/test_helper.rb
resolves: https://github.com/restarone/violet_rails/issues/830 no deploy needed
* try starting simplecov at rails boot to see if model coverage works
* undo
* prevent spring from running in test mode
* remove comment in env
=> [bug fix] resolve test coverage of models reports 0% (#929)

test/fixtures/api_actions.yml, test/fixtures/api_namespaces.yml, test/fixtures/api_resources.yml, test/fixtures/external_api_clients.yml, test/plugins/bishop_monitoring_plugin_test.rb, test/plugins/bishop_tls_monitoring_plugin_test.rb
add tests for plugins created in: https://github.com/restarone/violet_rails/issues/623
=> add tests for bishop monitoring plugin  (#911)

app/models/concerns/dynamic_attribute.rb, test/models/concerns/dynamic_attribute_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/934
=> safe executable ERB in dynamic segments in API

app/controllers/concerns/api_actionable.rb, app/helpers/ahoy_events_helper.rb, app/models/ahoy/event.rb, app/models/api_resource.rb, app/views/comfy/admin/api_resources/show.html.haml, test/controllers/resource_controller_test.rb, test/helpers/ahoy_events_helper_test.rb, test/models/api_resource_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/900
=> attach current_visit and current_user to created API Resource

app/views/comfy/admin/api_namespaces/show.html.haml, test/controllers/admin/comfy/api_namespaces_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/871
**Demo:**
https://user-images.githubusercontent.com/25191509/179969416-1d807c22-9c82-46d1-91b9-bc27bbdbce2c.mp4
=> [Violet Rails Core]: show dynamic attributes in API Resources index table

README.md, app/controllers/comfy/admin/api_namespaces_controller.rb, app/controllers/comfy/admin/api_resources_controller.rb, app/controllers/concerns/api_actionable.rb, app/controllers/resource_controller.rb, app/helpers/application_helper.rb, app/javascript/packs/comfy/admin/cms.js, app/models/api_action.rb, app/models/custom_api_action.rb, app/views/comfy/admin/api_actions/_form.html.haml, app/views/comfy/admin/api_actions/action_workflow.html.haml, app/views/comfy/admin/api_actions/show.html.haml, db/migrate/20220521032523_add_method_definition_to_api_actions.rb, db/schema.rb, test/controllers/admin/comfy/api_resources_controller_test.rb, test/controllers/resource_controller_test.rb, test/fixtures/api_actions.yml, test/fixtures/api_forms.yml, test/fixtures/api_namespaces.yml, test/models/api_action_test.rb
resolves: https://github.com/restarone/violet_rails/issues/527
=> [feature] custom API Actions

app/controllers/application_controller.rb, test/controllers/content_controller_test.rb, test/controllers/users/sessions_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/915
=> WIP: [Bug Fix] User not redirected properly after sign in

app/views/comfy/admin/api_namespaces/_editor.haml
=> Render rich text or file content on a new line in API

app/views/comfy/admin/api_namespaces/_editor.haml
=> [feature] Render rich text or file content on a new line in API

app/views/comfy/admin/api_resources/show.html.haml
last minute change for conditionally render visit details (https://github.com/restarone/violet_rails/issues/900)
=> conditionally render visit details

app/controllers/application_controller.rb, test/controllers/content_controller_test.rb, test/controllers/users/sessions_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/915
* fix(): saving the initial url for redirection
* feat(): refactor and add test case
* feat(): fix test case
=> [Bug Fix] User not redirected to previous location after sign in (#956)

app/helpers/ahoy_events_helper.rb, app/helpers/simple_discussion/forum_posts_helper.rb, app/models/forum_post.rb, app/models/forum_thread.rb, app/models/user.rb, app/views/comfy/admin/users/_form.haml, app/views/simple_discussion/forum_posts/_forum_post.html.erb, app/views/simple_discussion/forum_threads/_forum_thread.html.erb, app/views/simple_discussion/forum_threads/show.html.erb, test/controllers/admin/comfy/users_controller_test.rb, test/controllers/simple_discussion/forum_threads_controller_test.rb, test/helpers/ahoy_events_helper_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/924
**Demo**
https://user-images.githubusercontent.com/25191509/180488253-0c7f890a-9731-4cba-b8d0-0f2759145e90.mp4
=> [Bug fix]: can't delete user if they have forum post subscriptions

app/controllers/concerns/api_actionable.rb, app/controllers/resource_controller.rb, test/controllers/resource_controller_test.rb, test/fixtures/api_namespaces.yml
Addresses: https://github.com/restarone/violet_rails/issues/949
https://user-images.githubusercontent.com/35935196/180993751-4c773627-5b41-4c93-a88e-8bcdd89ac2f0.mov
=> [Bug Fix] Redirect back if no redirect action is defined

app/controllers/concerns/api_actionable.rb, app/controllers/resource_controller.rb, app/views/comfy/admin/api_forms/_render.haml, app/views/shared/_flash.haml, app/views/shared/_flash_content.haml, app/views/shared/flash.js.erb, app/views/shared/redirect.js.erb, test/controllers/admin/comfy/api_resources_controller_test.rb, test/controllers/resource_controller_test.rb
Addresses:  https://github.com/restarone/violet_rails/issues/917
Demo: 
https://user-images.githubusercontent.com/35935196/181828237-37c9093c-37fc-4046-ab50-1d53d2899423.mov
=> No redirection on form submission failure

app/controllers/concerns/api_actionable.rb, app/controllers/resource_controller.rb, app/views/comfy/admin/api_forms/_render.haml, app/views/shared/fallback_to_recaptcha_v2.js.erb, test/controllers/resource_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/916
https://user-images.githubusercontent.com/25191509/182033120-061b7e9a-836c-4f72-8fe4-ed5da43083ac.mp4
=> [Bug Fix] Silent recaptcha with challenge if confidence is low

app/controllers/concerns/api_actionable.rb, app/controllers/resource_controller.rb, app/views/comfy/admin/api_forms/_render.haml, app/views/shared/fallback_to_recaptcha_v2.js.erb, test/controllers/resource_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/916
https://user-images.githubusercontent.com/25191509/182033120-061b7e9a-836c-4f72-8fe4-ed5da43083ac.mp4
`Nikean.org` uses recaptcha V3 and present a challenge if bot-like behavior is detected. 
https://user-images.githubusercontent.com/35935196/182044455-b7386aec-f2eb-4a93-b89b-a3906b81f6e1.mov
=>  [Bug Fix] Silent recaptcha with challenge if confidence is low

app/controllers/api/resource_controller.rb, app/graphql/types/api_resource_type.rb, app/graphql/types/non_primitive_property_type.rb, app/models/non_primitive_property.rb, app/models/subdomain.rb, app/serializers/api_namespace_serializer.rb, app/serializers/api_resource_serializer.rb, app/serializers/non_primitive_property_serializer.rb, app/views/comfy/admin/api_namespaces/show.html.haml, test/controllers/api/resource_controller_test.rb, test/controllers/graphql_controller_test.rb, test/models/subdomain_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/875
=> [Feature] return non primitive types in REST API and GraphQL response

app/controllers/concerns/api_actionable.rb, app/controllers/resource_controller.rb, app/views/shared/render_recaptcha_with_error.js.erb, app/views/shared/reset_recaptcha_with_error.js.erb, test/controllers/resource_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/989
=> rerender recaptcha if recaptcha verification fails

public/404.html, public/500.html
Addresses #835 
404 page:
500 page:
=> Add custom 404/500 pages

public/404.html, public/500.html
Addresses #835 
404 page:
500 page:
=> [feature] branded 404/500 pages

public/404.html, public/500.html
* [feature] branded 404/500 pages 
Addresses #835 
404 page:
500 page:
* adjust
Co-authored-by: Mushfiq Rahman <mushfiqurrahman78@yahoo.com>
Co-authored-by: donrestarone <shashikejayatunge@gmail.com>
=> [feature] branded 404/500 pages (#1007)

app/helpers/content_helper.rb, test/fixtures/comfy/cms/snippets.yml, test/helpers/content_helper_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/271
https://user-images.githubusercontent.com/35935196/183777190-e9c330e1-f89a-4751-a34f-4a8de1abda23.mov
=> Conditional render snippet based on user session

app/controllers/concerns/api_actionable.rb, app/controllers/resource_controller.rb, test/controllers/resource_controller_test.rb, test/fixtures/api_namespaces.yml
Addresses: https://github.com/restarone/violet_rails/issues/949
https://user-images.githubusercontent.com/35935196/180993751-4c773627-5b41-4c93-a88e-8bcdd89ac2f0.mov
=> [Bug Fix] Redirect back if no redirect action is defined  (#979)

app/controllers/concerns/api_actionable.rb, app/controllers/resource_controller.rb, app/views/comfy/admin/api_forms/_render.haml, app/views/shared/reset_recaptcha_with_error.js.erb, test/controllers/resource_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/989
https://user-images.githubusercontent.com/35935196/182979819-02367185-7a11-4dd8-84e2-b4788750ece8.mov
=> [feature] rerender recaptcha if recaptcha verification fails

app/javascript/packs/application.js, app/views/comfy/admin/api_forms/_render.haml
Ref: 
- https://github.com/ambethia/recaptcha/wiki/Recaptcha-with-Turbo-and-Stimulus
- https://github.com/ambethia/recaptcha/issues/217
=> [bug fix] handle Recaptcha with turbo

app/controllers/comfy/admin/api_namespaces_controller.rb, app/views/comfy/admin/api_namespaces/export_api_resources.csv.haml, app/views/comfy/admin/api_namespaces/show.html.haml, config/routes.rb, test/controllers/admin/comfy/api_namespaces_controller_test.rb, test/fixtures/api_resources.yml
Addresses: https://github.com/restarone/violet_rails/issues/1014
https://user-images.githubusercontent.com/25191509/184860936-e3c58c0c-d836-4c51-8799-2f64dceb6b5b.mp4
=> [Violet Rails Core]: Ability to download csv of api resources

app/controllers/comfy/admin/api_namespaces_controller.rb, app/views/comfy/admin/api_namespaces/export_api_resources.csv.haml, app/views/comfy/admin/api_namespaces/show.html.haml, config/routes.rb, test/controllers/admin/comfy/api_namespaces_controller_test.rb, test/fixtures/api_resources.yml
Addresses: https://github.com/restarone/violet_rails/issues/1014
https://user-images.githubusercontent.com/25191509/184860936-e3c58c0c-d836-4c51-8799-2f64dceb6b5b.mp4
=> [feature]: Ability to download CSV of API resources (#1022)

app/controllers/comfy/admin/api_namespaces_controller.rb, app/views/comfy/admin/api_namespaces/export_api_resources.csv.haml, app/views/comfy/admin/api_namespaces/show.html.haml, config/routes.rb, test/controllers/admin/comfy/api_namespaces_controller_test.rb, test/fixtures/api_resources.yml
Addresses: https://github.com/restarone/violet_rails/issues/1014
https://user-images.githubusercontent.com/25191509/184860936-e3c58c0c-d836-4c51-8799-2f64dceb6b5b.mp4
=> [feature]: Ability to download CSV of API resources (#1022) (#1026)

app/assets/stylesheets/application.scss, app/helpers/api_resources_helper.rb, app/javascript/packs/common.js, app/views/api_action_mailer/send_email.html.erb, app/views/comfy/admin/api_forms/_render.haml, app/views/comfy/admin/api_namespaces/_editor.haml
Addresses: https://github.com/restarone/violet_rails/issues/980
https://user-images.githubusercontent.com/25191509/185351232-f54d0792-dcfc-4af7-ad05-ce7486da72da.mp4
=> [feature]: Render API Resource file attachment if representable (eg: video/ image)

app/controllers/concerns/api_actionable.rb, app/controllers/resource_controller.rb, app/views/shared/reset_recaptcha_with_error.js.erb, test/controllers/resource_controller_test.rb
* [feature]: Ability to download CSV of API resources (#1022) (#1026)
Addresses: https://github.com/restarone/violet_rails/issues/1014
https://user-images.githubusercontent.com/25191509/184860936-e3c58c0c-d836-4c51-8799-2f64dceb6b5b.mp4
* Revert "[feature] rerender recaptcha if recaptcha verification fails"
This reverts commit ceaee668d913a8db62032ea75005030b5972b0b5.
Co-authored-by: Shashike Jayatunge <35935196+donrestarone@users.noreply.github.com>
=> [feature] rerender recaptcha if recaptcha fails 

app/controllers/concerns/api_actionable.rb, app/models/api_action.rb, app/models/api_resource.rb, app/sidekiq/external_api_client_job.rb, app/sidekiq/fire_api_actions_job.rb, test/controllers/admin/comfy/api_resources_controller_test.rb, test/controllers/resource_controller_test.rb, test/fixtures/api_actions.yml, test/fixtures/api_namespaces.yml, test/fixtures/external_api_clients.yml, test/models/api_resource_test.rb, test/models/external_api_client_test.rb, test/plugins/bishop_monitoring_plugin_test.rb, test/plugins/bishop_tls_monitoring_plugin_test.rb, test/test_helper.rb
Addresses: https://github.com/restarone/violet_rails/issues/584
=> [feature]: Fire api actions from model (#1012)

app/controllers/concerns/api_actionable.rb, app/models/api_action.rb, app/models/api_resource.rb, app/sidekiq/external_api_client_job.rb, app/sidekiq/fire_api_actions_job.rb, test/controllers/admin/comfy/api_resources_controller_test.rb, test/controllers/resource_controller_test.rb, test/fixtures/api_actions.yml, test/fixtures/api_namespaces.yml, test/fixtures/external_api_clients.yml, test/models/api_resource_test.rb, test/models/external_api_client_test.rb, test/plugins/bishop_monitoring_plugin_test.rb, test/plugins/bishop_tls_monitoring_plugin_test.rb, test/test_helper.rb
Addresses: https://github.com/restarone/violet_rails/issues/584
=> [feature]: Fire api actions from model (#1012) (#1027)

app/assets/stylesheets/application.scss, app/helpers/api_resources_helper.rb, app/javascript/packs/common.js, app/views/api_action_mailer/send_email.html.erb, app/views/comfy/admin/api_forms/_render.haml, app/views/comfy/admin/api_namespaces/_editor.haml
Addresses: https://github.com/restarone/violet_rails/issues/980
https://user-images.githubusercontent.com/25191509/185351232-f54d0792-dcfc-4af7-ad05-ce7486da72da.mp4
=> [feature]: Render API Resource file attachment if representable 

app/assets/stylesheets/application.scss, app/helpers/api_resources_helper.rb, app/javascript/packs/common.js, app/views/api_action_mailer/send_email.html.erb, app/views/comfy/admin/api_forms/_render.haml, app/views/comfy/admin/api_namespaces/_editor.haml
Addresses: https://github.com/restarone/violet_rails/issues/980
https://user-images.githubusercontent.com/25191509/185351232-f54d0792-dcfc-4af7-ad05-ce7486da72da.mp4
=> [feature] Render API Resource file attachment if representable

app/controllers/application_controller.rb, app/helpers/content_helper.rb, app/models/api_resource.rb, app/models/comfy/cms/snippet.rb, app/models/concerns/dynamic_attribute.rb, app/models/user.rb, db/migrate/20220819052000_add_user_to_api_resource.rb, db/schema.rb, test/controllers/admin/comfy/api_namespaces_controller_test.rb, test/helpers/content_helper_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/267
https://user-images.githubusercontent.com/35935196/185770631-67a9aed9-bc09-47bd-b437-17e35cc824c6.mov
=> Api html renderer

app/assets/stylesheets/cookies.scss, db/migrate/20220824121504_add_cookies_consent_ui_to_subdomain.rb
=> Update cookie consent markup and styling

app/views/comfy/admin/api_namespaces/export_api_resources.csv.haml, test/controllers/admin/comfy/api_namespaces_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1061
**Demo**
https://user-images.githubusercontent.com/25191509/187054661-bd5c209b-58ba-4564-8f0b-338a6f864858.mp4
=> [feature]: Include non primitive types in csv export

app/views/comfy/admin/api_namespaces/export_api_resources.csv.haml, test/controllers/admin/comfy/api_namespaces_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1061
**Demo**
https://user-images.githubusercontent.com/25191509/187054661-bd5c209b-58ba-4564-8f0b-338a6f864858.mp4
=> [feature] Include non primitive types in csv export

app/controllers/comfy/admin/cms/layouts_controller.rb, test/controllers/admin/comfy/admin_controller_test.rb, test/controllers/admin/comfy/layouts_controller_test.rb, test/fixtures/comfy/cms/layouts.yml
Addresses: https://github.com/restarone/violet_rails/issues/1089
https://user-images.githubusercontent.com/25191509/189512814-53ccb975-d6d7-4831-a329-edbb1263c66e.mp4
=> [Bug Fix]: Cannot create new layout

app/controllers/comfy/admin/cms/layouts_controller.rb, test/controllers/admin/comfy/admin_controller_test.rb, test/controllers/admin/comfy/layouts_controller_test.rb, test/fixtures/comfy/cms/layouts.yml
Addresses: https://github.com/restarone/violet_rails/issues/1089
https://user-images.githubusercontent.com/25191509/189512814-53ccb975-d6d7-4831-a329-edbb1263c66e.mp4
=> [Bug Fix] Cannot create new layout

app/controllers/application_controller.rb, app/helpers/content_helper.rb, app/models/api_resource.rb, app/models/comfy/cms/snippet.rb, app/models/concerns/dynamic_attribute.rb, app/models/concerns/jsonb_search/sortable.rb, app/models/user.rb, db/migrate/20220819052000_add_user_to_api_resource.rb, db/schema.rb, test/controllers/admin/comfy/api_namespaces_controller_test.rb, test/helpers/content_helper_test.rb, test/models/api_resource_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/267
guide for querying: https://github.com/restarone/violet_rails/pull/995 *need better docs*
https://user-images.githubusercontent.com/35935196/185770631-67a9aed9-bc09-47bd-b437-17e35cc824c6.mov
https://user-images.githubusercontent.com/50227291/188428768-00232faa-7fc0-4bf7-aae4-3e6714c171a8.mov
- create snippet with identifier same as api_namespace slug
- Variables available on snippet: @api_resources & @api_namespace
- Render the snippet on any page with this helper: {{cms:helper render_api_namespace_resource_index 'identifier'}}
- Is filterable using query params, eg: http://lvh.me:5250/?properties={"synced":"false"}
- create snippet with  identifier as api_namespace slug with '-show' at the end, eg: people-show
- Variables …
=> [feature] API HTML renderer (#1047)

app/controllers/concerns/api_actionable.rb, app/controllers/resource_controller.rb, app/views/comfy/admin/api_forms/_render.haml, app/views/shared/fallback_to_recaptcha_v2.js.erb
Addresses: https://github.com/restarone/violet_rails/issues/1110
=> [WIP] Multiple api form on the same page

app/controllers/concerns/api_actionable.rb, app/controllers/resource_controller.rb, app/views/comfy/admin/api_forms/_render.haml, app/views/shared/fallback_to_recaptcha_v2.js.erb
[bug fix] resolve use API form (recaptcha v3) multiple times on the same page
Addresses: https://github.com/restarone/violet_rails/issues/1110
=> [bug fix] resolve use API form (recaptcha v3) multiple times on the same page

app/controllers/concerns/api_actionable.rb, app/controllers/resource_controller.rb, app/views/comfy/admin/api_forms/_render.haml, app/views/shared/fallback_to_recaptcha_v2.js.erb
[bug fix] resolve use API form (recaptcha v3) multiple times on the same page
Addresses: https://github.com/restarone/violet_rails/issues/1110
=> [bug fix] resolve use API form (recaptcha v3) multiple times on the same page (#1114)

app/helpers/content_helper.rb, app/models/concerns/jsonb_search/query_builder.rb, test/helpers/content_helper_test.rb, test/models/concerns/jsonb_search/query_builder_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/267, https://github.com/restarone/violet_rails/pull/1047#issuecomment-1249379969
Returns records that contains both of given values `render_api_namespace_resource_index(@api_namespace.slug, { 'scope' => { 'properties' => { 'tags': { 'value': ['not action', 'comedy'], option: 'PARTIAL', match: 'ALL'} } } })`
Returns records that contains atleast one of given values `render_api_namespace_resource_index(@api_namespace.slug, { 'scope' => { 'properties' => { 'tags': { 'value': ['not action', 'comedy'], option: 'PARTIAL', match: 'ANY'} } } })`
`render_api_namespace_resource_index(@api_namespace.slug, { 'limit': 10 })`
=> [feature] API renderer Allow ALL/ANY + limit resources

app/mailers/e_mailer.rb, app/services/violet/connection.rb, app/services/violet/connection_service.rb, test/fixtures/api_namespaces.yml, test/fixtures/api_resources.yml, test/fixtures/external_api_clients.yml, test/plugins/compliance_visitor_data_request_plugin_test.rb
=> Compliance visitor data request plugin

app/controllers/comfy/admin/api_namespaces_controller.rb, app/models/api_resource.rb, app/views/comfy/admin/api_namespaces/show.html.haml, test/controllers/admin/comfy/api_namespaces_controller_test.rb
=> allow sorting with fields inside properties

app/controllers/comfy/admin/api_namespaces_controller.rb, app/models/api_resource.rb, app/views/comfy/admin/api_namespaces/show.html.haml, test/controllers/admin/comfy/api_namespaces_controller_test.rb
Addresses #1119 
https://user-images.githubusercontent.com/35935196/193003658-6d7166b6-35ec-4837-af1c-11ac12b9d095.mp4
=> [feature] sort by attribute in API Namespace resource index

app/models/concerns/dynamic_attribute.rb, test/helpers/content_helper_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1109 
Screenshots:
=> Allow active support / view helpers in API Renderer.

app/controllers/comfy/admin/api_namespaces_controller.rb, app/models/api_resource.rb, app/views/comfy/admin/api_namespaces/show.html.haml, test/controllers/admin/comfy/api_namespaces_controller_test.rb
Addresses #1119 
https://user-images.githubusercontent.com/19350071/192568284-c8c0e8f1-d777-45f0-9847-4b3131af99fb.mp4
Co-authored-by: Aashutosh Poudel <aashutoshpoudyal@gmail.com>
=> [feature] sort by attribute in API Namespace resource index (#1138)

app/models/concerns/dynamic_attribute.rb, test/helpers/content_helper_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1109 
Screenshots:
Co-authored-by: Sushmit Rajaure <Sushmit@Sushmits-MacBook-Pro.local>
=> [feature] Allow active support / view helpers in API Renderer

config/initializers/force_ssl.rb
Addresses: [#1149](https://github.com/restarone/violet_rails/issues/1149)
- Add config to load assets over https for staging and production.
=> Load assests over https

app/models/api_action.rb, app/sidekiq/fire_api_actions_job.rb, test/controllers/resource_controller_test.rb
Demo
https://user-images.githubusercontent.com/50227291/196223270-e1d831f3-8403-43eb-84c2-d5419ea078d4.mov
=> run error api action only after final retry

app/models/concerns/jsonb_search/query_builder.rb, test/helpers/content_helper_test.rb, test/models/concerns/jsonb_search/query_builder_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1154
Demo:
Before:
https://user-images.githubusercontent.com/50227291/197104588-91763df2-6ca7-4f25-9413-1153140abdb7.mov
After:
https://user-images.githubusercontent.com/50227291/197104624-dc6d9e2b-3dc6-4737-87c2-705a16772a51.mov
=> hanlde jsonb search with quotes

app/models/concerns/jsonb_search/query_builder.rb, test/helpers/content_helper_test.rb, test/models/concerns/jsonb_search/query_builder_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1154
Demo:
Before:
https://user-images.githubusercontent.com/50227291/197104588-91763df2-6ca7-4f25-9413-1153140abdb7.mov
After:
https://user-images.githubusercontent.com/50227291/197104624-dc6d9e2b-3dc6-4737-87c2-705a16772a51.mov
=> [bug fix] resolve API resource query error when apostrophe (') is included

.buildpacks, .github/workflows/dokku-deploy.yml, Procfile, bin/ci-pre-deploy
Addresses: https://github.com/restarone/violet_rails/issues/1127
- The base branch of the PR needs to be `master`/`dev`/`rc` for the dokku CI to run.
- The url of the new review-app will be: `review-[PR number].violet-test.net`. A comment will be added after the deployment of review-app is successful as in image below:
- Since the database of review-app is a clone of database of heroku's violet-rails, you can use the same login credentials used in heroku to login.
- While creating the PR which has label: `deploy-review-app`
- When a closed PR with label: `deploy-review-app` is reopened
- While labeling the open PR with `deploy-review-app`
- When new commits are pushed to the open PR which already have the label: `deploy-review-app`
- While closing/mergin the PR which has label: …
=> [feature] Dokku integration for testnet

app/controllers/comfy/admin/api_actions_controller.rb, app/controllers/comfy/admin/api_clients_controller.rb, app/controllers/comfy/admin/api_forms_controller.rb, app/controllers/comfy/admin/api_namespaces_controller.rb, app/controllers/comfy/admin/api_resources_controller.rb, app/controllers/comfy/admin/external_api_clients_controller.rb, app/controllers/comfy/admin/users_controller.rb, app/controllers/subdomains/base_controller.rb, app/models/user.rb, app/views/comfy/admin/api_actions/action_workflow.html.haml, app/views/comfy/admin/api_namespaces/show.html.haml, app/views/comfy/admin/users/_api_accessibility.haml, app/views/comfy/admin/users/_form.haml, app/views/comfy/admin/users/index.html.haml, config/routes.rb, db/migrate/20220913021415_add_api_accessibility_to_users.rb, db/migrate/20220917134117_remove_can_manage_api_from_users_and_back_fill_api_accessibility.rb, db/schema.rb, test/controllers/admin/comfy/api_actions_controller_test.rb, test/controllers/admin/comfy/api_clients_controller_test.rb, test/controllers/admin/comfy/api_forms_controller_test.rb, test/controllers/admin/comfy/api_namespaces_controller_test.rb, test/controllers/admin/comfy/api_resources_controller_test.rb, test/controllers/admin/comfy/external_api_clients_controller_test.rb, test/controllers/admin/comfy/users_controller_test.rb, test/controllers/users/sessions_controller_test.rb, test/plugins/bishop_monitoring_plugin_test.rb, test/plugins/bishop_tls_monitoring_plugin_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1075
https://user-images.githubusercontent.com/35935196/191496793-30d7e50f-7674-489f-bb30-699fa4ab02f6.mp4
=> [feature] allow access to API by category

.github/workflows/dokku-deploy.yml, bin/ci-pre-deploy
Address: https://github.com/restarone/violet_rails/issues/1127
=> [Dokku CI] create separate redis service for the review-apps in dokku-CI

app/controllers/comfy/admin/api_namespaces_controller.rb, app/helpers/content_helper.rb, app/helpers/subdomain_helper.rb, app/views/comfy/admin/api_namespaces/show.html.haml, app/views/shared/_meta_tags.html.erb, config/routes.rb, db/migrate/20221025091924_add_metadata_to_api_namespaces.rb, db/schema.rb, test/controllers/admin/comfy/api_namespaces_controller_test.rb, test/helpers/subdomain_helper_test.rb
Addresses : https://github.com/restarone/violet_rails/issues/1166
Demo: 
https://user-images.githubusercontent.com/55496123/198818845-c131640a-9dbb-4e57-9113-b45b713f9d48.mov
=> [Feature] Social Sharing Metadata Option in API Namespace

app/models/api_namespace.rb, app/views/comfy/admin/api_namespaces/index.html.haml, app/views/comfy/admin/api_namespaces/show.html.haml, test/controllers/admin/comfy/api_namespaces_controller_test.rb, test/models/api_namespace_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/974
**Demo**
https://user-images.githubusercontent.com/25191509/199165299-25d1e0fb-0cd1-49a4-8e66-224bca2fa660.mov
=> [Violet Rails Core] link to associated CMS entity in API

.github/workflows/dokku-deploy.yml, bin/ci-pre-deploy
Address: https://github.com/restarone/violet_rails/issues/1127
=> [CI] create separate redis service for the review-apps in dokku-CI

app/controllers/comfy/admin/api_namespaces_controller.rb, app/helpers/content_helper.rb, app/helpers/subdomain_helper.rb, app/views/comfy/admin/api_namespaces/show.html.haml, app/views/shared/_meta_tags.html.erb, config/routes.rb, db/migrate/20221025091924_add_metadata_to_api_namespaces.rb, db/schema.rb, test/controllers/admin/comfy/api_namespaces_controller_test.rb, test/helpers/subdomain_helper_test.rb
Addresses : https://github.com/restarone/violet_rails/issues/1166
Demo: 
https://user-images.githubusercontent.com/55496123/198818845-c131640a-9dbb-4e57-9113-b45b713f9d48.mov
=> [Feature] Social Sharing Metadata Option in API Namespace (#1174)

app/controllers/comfy/admin/api_namespaces_controller.rb, app/helpers/content_helper.rb, app/helpers/subdomain_helper.rb, app/models/non_primitive_property.rb, app/views/comfy/admin/api_namespaces/show.html.haml, app/views/shared/_meta_tags.html.erb, config/routes.rb, db/migrate/20221025091924_add_metadata_to_api_namespaces.rb, db/schema.rb, test/controllers/admin/comfy/api_namespaces_controller_test.rb, test/helpers/subdomain_helper_test.rb
* [Feature] Social Sharing Metadata Option in API Namespace (#1174)
Addresses : https://github.com/restarone/violet_rails/issues/1166
Demo: 
https://user-images.githubusercontent.com/55496123/198818845-c131640a-9dbb-4e57-9113-b45b713f9d48.mov
* image height and weight added for metatags
Co-authored-by: Er. Ajay Shrestha <55496123+ajaystha42@users.noreply.github.com>
Co-authored-by: Ajay Shrestha <er.ajaystha@gmail.com>
=> [Feature] Social Sharing Metadata Option in API Namespace (#1191)

app/assets/stylesheets/application.scss, app/assets/stylesheets/direct_upload.scss, app/helpers/api_forms_helper.rb, app/javascript/packs/common.js, app/javascript/packs/direct_upload.js
Addresses: https://github.com/restarone/violet_rails/issues/1112
Demo:
https://user-images.githubusercontent.com/50227291/194333126-48e3f94a-7b88-4e47-8cd2-761caea476ee.mov
https://user-images.githubusercontent.com/50227291/194479010-025da92e-f82f-413b-b474-3ca09704b037.mov
=> [feature] upload file before form submission

app/assets/stylesheets/application.scss, app/assets/stylesheets/direct_upload.scss, app/helpers/api_forms_helper.rb, app/javascript/packs/common.js, app/javascript/packs/direct_upload.js
Addresses: https://github.com/restarone/violet_rails/issues/1112
Demo:
https://user-images.githubusercontent.com/50227291/194333126-48e3f94a-7b88-4e47-8cd2-761caea476ee.mov
https://user-images.githubusercontent.com/50227291/194479010-025da92e-f82f-413b-b474-3ca09704b037.mov
=> [feature] upload file before form submission (#1155)

.github/workflows/dokku-clean-review-apps.yml
=> [CI] Job to delete all review apps

.github/workflows/dokku-clean-review-apps.yml
This manually-run job destroys all reviews apps on https://violet-test.net except for the main review application hosted at the application root
=> [CI] Job to delete all review apps (#1206)

.github/workflows/dokku-clean-review-apps.yml
=> [patch] bash script error for cleaning dokku review-apps (#1208)

app/controllers/comfy/admin/api_namespaces_controller.rb, app/models/api_namespace.rb, app/views/comfy/admin/api_namespaces/index.html.haml, app/views/comfy/admin/api_namespaces/show.html.haml, test/controllers/admin/comfy/api_namespaces_controller_test.rb, test/models/api_namespace_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/974
**Demo**
https://user-images.githubusercontent.com/25191509/199165299-25d1e0fb-0cd1-49a4-8e66-224bca2fa660.mov
=> [feature] link to associated CMS entity in API

app/models/forum_category.rb, test/controllers/simple_discussion/forum_categories_controller_test.rb
Addresses https://github.com/restarone/violet_rails/issues/1186
Demo video:
https://user-images.githubusercontent.com/39255317/200030590-10ea89cb-533d-450e-b393-6874b63509e3.mov
=> [bug fix] Forum category slug empty case bug patched and test case added

app/models/concerns/safe_executable_validator.rb, test/fixtures/external_api_clients.yml, test/models/external_api_client_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1144
=> [Violet Rails Core]: Prevent raw sql usage in api

app/models/forum_category.rb, test/controllers/simple_discussion/forum_categories_controller_test.rb
Addresses https://github.com/restarone/violet_rails/issues/1186
Demo video:
https://user-images.githubusercontent.com/39255317/200030590-10ea89cb-533d-450e-b393-6874b63509e3.mov
=> [bug fix] cant change/create category in forum

app/models/forum_category.rb, test/controllers/simple_discussion/forum_categories_controller_test.rb
Addresses https://github.com/restarone/violet_rails/issues/1186
Demo video:
https://user-images.githubusercontent.com/39255317/200030590-10ea89cb-533d-450e-b393-6874b63509e3.mov
Co-authored-by: Sushmit Rajaure <39255317+Sushmit1997@users.noreply.github.com>
=> [bug fix] cant change/create category in forum (#1219)

app/models/concerns/safe_executable_validator.rb, test/fixtures/external_api_clients.yml, test/models/external_api_client_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1144
=> [feature] Prevent raw sql usage in API

app/models/concerns/safe_executable_validator.rb, test/fixtures/external_api_clients.yml, test/models/external_api_client_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1144
=> [feature] Prevent raw SQL usage in API (#1220)

app/controllers/comfy/admin/web_settings_controller.rb, app/mailers/simple_discussion/user_mailer.rb, app/models/subdomain.rb, app/views/comfy/admin/web_settings/_form.haml, db/migrate/20221104133642_add_email_notification_strategy_to_subdomain.rb, db/schema.rb, test/mailers/simple_discussion/user_mailer_test.rb, test/models/subdomain_test.rb
Addresses : https://github.com/restarone/violet_rails/issues/1169
Demo video :
https://user-images.githubusercontent.com/39255317/198045816-b7ee4333-e5a3-4875-9a18-0ed5be1f9df4.mov
Co-authored-by: Sushmit Rajaure <Sushmit@Sushmits-MacBook-Pro.local>
=> [feature] ability to define forum email notification strategy

app/helpers/content_helper.rb, app/helpers/subdomain_helper.rb, app/views/shared/_meta_tags.html.erb, test/helpers/subdomain_helper_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1199
=> Fix social share meta data mapping

app/helpers/content_helper.rb, app/helpers/subdomain_helper.rb, app/views/shared/_meta_tags.html.erb, test/helpers/subdomain_helper_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1199
=> [bug fix]  social share meta data mapping (#1227)

app/views/layouts/comfy/admin/cms/_footer_js.html.haml
https://github.com/restarone/violet_rails/issues/1214
Demo: 
https://user-images.githubusercontent.com/55496123/201949004-d3e26a1d-04f0-4afb-ae50-5e63e6bf16cb.mov
=> bugfix: JS Issue fix after user accepts the cookie consent on Ordinary Trip

app/helpers/content_helper.rb, app/helpers/subdomain_helper.rb, app/views/shared/_meta_tags.html.erb, test/helpers/subdomain_helper_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1199
=> [bug fix]  social share meta data mapping (#1227) (#1229)

app/controllers/users/invitations_controller.rb, test/controllers/users/invitations_controller_test.rb, test/controllers/users/registrations_controller_test.rb, test/controllers/users/sessions_controller_test.rb
addresses: https://github.com/restarone/violet_rails/issues/1248
=> [bug fix]: user cannot sign up when subdomain has 2FA enabled

app/views/comfy/admin/api_namespaces/index.html.haml, app/views/comfy/admin/api_namespaces/show.html.haml, test/controllers/admin/comfy/api_namespaces_controller_test.rb
Addresses #1123 
https://user-images.githubusercontent.com/73725297/204039514-0b465231-10a6-40e1-a9e2-0f2a0e5eddaa.mp4
=> [feature] Unify form and renderer

app/views/comfy/admin/api_namespaces/index.html.haml, app/views/comfy/admin/api_namespaces/show.html.haml, test/controllers/admin/comfy/api_namespaces_controller_test.rb
Addresses #1123 
https://user-images.githubusercontent.com/73725297/204039514-0b465231-10a6-40e1-a9e2-0f2a0e5eddaa.mp4
Co-authored-by: Mushfiq Rahman <mushfiqurrahman78@yahoo.com>
=> [feature] Unify form and renderer (#1252)

app/assets/stylesheets/actiontext.scss, app/controllers/simple_discussion/application_controller.rb, app/controllers/simple_discussion/forum_posts_controller.rb, app/controllers/simple_discussion/forum_threads_controller.rb, app/javascript/packs/application.js, app/javascript/packs/tribute.js, app/models/forum_post.rb, app/models/forum_thread.rb, app/models/user.rb, app/views/simple_discussion/forum_posts/_form.html.erb, app/views/simple_discussion/forum_threads/_form.html.erb, app/views/users/_user.html.erb, config/locales/en.yml, package.json, test/controllers/simple_discussion/forum_threads_controller_test.rb, yarn.lock
Addresses: #1173 
Demo:
https://user-images.githubusercontent.com/18470532/199933805-7669b727-cd76-43ad-9125-c8be379973a6.mov
https://user-images.githubusercontent.com/18470532/200725154-1e9ce5f7-c7ed-4ec3-8b46-9c9bc232567f.mov
=> [feature] Ability to mention user in forum

app/assets/stylesheets/actiontext.scss, app/controllers/simple_discussion/application_controller.rb, app/controllers/simple_discussion/forum_posts_controller.rb, app/controllers/simple_discussion/forum_threads_controller.rb, app/javascript/packs/application.js, app/javascript/packs/tribute.js, app/models/forum_post.rb, app/models/forum_thread.rb, app/models/user.rb, app/views/simple_discussion/forum_posts/_form.html.erb, app/views/simple_discussion/forum_threads/_form.html.erb, app/views/users/_user.html.erb, config/locales/en.yml, package.json, test/controllers/simple_discussion/forum_threads_controller_test.rb, yarn.lock
Addresses: #1173 
Demo:
https://user-images.githubusercontent.com/18470532/199933805-7669b727-cd76-43ad-9125-c8be379973a6.mov
https://user-images.githubusercontent.com/18470532/200725154-1e9ce5f7-c7ed-4ec3-8b46-9c9bc232567f.mov
Co-authored-by: Ravi <rabigiri18@gmail.com>
Co-authored-by: Regaron <Regaron@users.noreply.github.com>
Co-authored-by: Prashant Khadka <25191509+alis-khadka@users.noreply.github.com>
=> [feature] Ability to mention user in forum (#1256)

app/controllers/application_controller.rb, app/controllers/concerns/ahoy_controller_patch.rb, app/controllers/cookies_controller.rb, app/views/comfy/admin/web_settings/_form.haml, app/views/shared/_cookies_consent_ui.html.erb, config/initializers/ahoy.rb, config/routes.rb, db/migrate/20221128055836_change_cookie_consent_ui_default_in_subdomain.rb, db/schema.rb, test/controllers/cookies_controller_test.rb, test/controllers/disk_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1235
**DEMO**
https://user-images.githubusercontent.com/25191509/204212777-ab22c487-d0aa-458c-981d-6f951df7cb2a.mov
=> [Bug Fix]: cookie consent is popping up too often and is not persisted

app/controllers/application_controller.rb, app/controllers/concerns/ahoy_controller_patch.rb, app/controllers/cookies_controller.rb, app/views/comfy/admin/web_settings/_form.haml, app/views/shared/_cookies_consent_ui.html.erb, config/initializers/ahoy.rb, config/routes.rb, db/migrate/20221128055836_change_cookie_consent_ui_default_in_subdomain.rb, db/schema.rb, test/controllers/cookies_controller_test.rb, test/controllers/disk_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1235
**DEMO**
to get cookie consent status, call endpoint:
``` txt
YOUR_DOMAIN/cookies/fetch
```
https://user-images.githubusercontent.com/25191509/204212777-ab22c487-d0aa-458c-981d-6f951df7cb2a.mov
=> [Bug Fix] cookie consent is popping up too often and is not persisted

app/controllers/application_controller.rb, app/controllers/concerns/ahoy_controller_patch.rb, app/controllers/cookies_controller.rb, app/views/comfy/admin/web_settings/_form.haml, app/views/shared/_cookies_consent_ui.html.erb, config/initializers/ahoy.rb, config/routes.rb, db/migrate/20221128055836_change_cookie_consent_ui_default_in_subdomain.rb, db/schema.rb, test/controllers/cookies_controller_test.rb, test/controllers/disk_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1235
**DEMO**
to get cookie consent status, call endpoint:
``` txt
YOUR_DOMAIN/cookies/fetch
```
https://user-images.githubusercontent.com/25191509/204212777-ab22c487-d0aa-458c-981d-6f951df7cb2a.mov
Co-authored-by: Prashant <25191509+alis-khadka@users.noreply.github.com>
=> [Bug Fix] cookie consent is popping up too often 

app/controllers/concerns/ahoy_controller_patch.rb, test/controllers/api/resource_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1269
=> [bug fix]: undefined `cookies' for Api::ResourceController

app/models/api_namespace.rb, app/views/comfy/admin/api_namespaces/_search_filters.haml, test/controllers/admin/comfy/api_namespaces_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1225
**Demo**
https://user-images.githubusercontent.com/25191509/201937978-4f162ef3-2b98-4ba1-9112-26e8ae53613e.mov
=> [bug fix] can't search by name in API #index

.github/workflows/brakeman-analysis.yml
Addresses: https://github.com/restarone/violet_rails/issues/1263
=> [CI] Fix brakeman scan

app/helpers/api_namespaces_helper.rb, test/controllers/admin/comfy/api_namespaces_controller_test.rb, test/fixtures/api_namespaces.yml, test/helpers/api_namespaces_helper_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1018
=> [Bug Fix]: fix generated documentation in API Namespace

app/helpers/api_namespaces_helper.rb, test/controllers/admin/comfy/api_namespaces_controller_test.rb, test/fixtures/api_namespaces.yml, test/helpers/api_namespaces_helper_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1018
Co-authored-by: Prashant <25191509+alis-khadka@users.noreply.github.com>
=> [Bug Fix] generated documentation in API Namespace

app/mailboxes/e_mailbox.rb, app/mailers/e_mailer.rb, app/models/message.rb, test/mailboxes/e_mailbox_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1234
=> [Bug Fix] resolve email threads

test/fixtures/api_actions.yml, test/fixtures/api_namespaces.yml, test/fixtures/api_resources.yml, test/plugins/timesheet_request_plugin_test.rb
existing code in https://team.restarone.solutions/api_namespaces/4/api_actions/action_workflow
=> [plugin] timesheet tracker

app/controllers/comfy/admin/api_actions_controller.rb, app/controllers/subdomains/base_controller.rb, app/helpers/api_accessibility_helper.rb, app/views/comfy/admin/api_actions/_form.html.haml, app/views/comfy/admin/api_actions/action_workflow.html.haml, app/views/comfy/admin/api_namespaces/_form.html.haml, app/views/comfy/admin/cms/categories/_form.html.haml, test/controllers/admin/comfy/api_actions_controller_test.rb, test/controllers/admin/comfy/api_namespaces_controller_test.rb, test/fixtures/comfy/cms/categories.yml, test/helpers/api_accessibility_helper_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1315
**Demo**
https://user-images.githubusercontent.com/25191509/209044452-9db5a0f7-8037-4561-bdf9-0f06c99a6508.mov
=> [feature] Uncategorized access should allow API Namespace creation

app/helpers/application_helper.rb, app/views/shared/_cookies_consent_ui.html.erb, test/controllers/admin/comfy/cms/content_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1213
**Demo**
https://user-images.githubusercontent.com/25191509/210127762-7c9d70f2-0aae-4bc5-820b-8893f9b27de7.mov
=> [feature] integrate CMS with cookie consent UI

app/controllers/comfy/admin/users_controller.rb, app/controllers/simple_discussion/application_controller.rb, app/controllers/simple_discussion/forum_posts_controller.rb, app/controllers/simple_discussion/forum_threads_controller.rb, app/views/comfy/admin/users/_form.haml, app/views/simple_discussion/forum_threads/show.html.erb, db/migrate/20221230035120_add_can_access_forum_to_users.rb, db/schema.rb, test/controllers/simple_discussion/forum_categories_controller_test.rb, test/controllers/simple_discussion/forum_posts_controller_test.rb, test/controllers/simple_discussion/forum_threads_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1305
**Demo**
https://user-images.githubusercontent.com/25191509/210078509-2b229519-0028-4b4a-8c59-7f5c9d2d137f.mov
=> [feature] permissioned forum access

.github/workflows/deploy.yml
Addresses: https://github.com/restarone/violet_rails/issues/1301
=> [nikean.org]using ubuntu-latest in capistrano deployment 

.github/workflows/deploy.yml
Addresses: https://github.com/restarone/violet_rails/issues/1312
=> [Violet Rails CI]: stop using set-output in CI

.github/workflows/deploy.yml
Addresses: https://github.com/restarone/violet_rails/issues/1312
Addresses: https://github.com/restarone/violet_rails/issues/1301
=> no set-output in CI + use ubuntu-latest in cap deploy

app/views/comfy/admin/users/_form.haml
Addresses: https://github.com/restarone/violet_rails/issues/1339
**Demo**
https://user-images.githubusercontent.com/25191509/211619898-53519689-be23-47fa-a2df-2daebb524bd0.mov
=> [Bug Fix]: cannot grant forum access

app/views/comfy/admin/users/_form.haml
Addresses: https://github.com/restarone/violet_rails/issues/1301
=> [CI/CD] use ubuntu-latest for Cap deploy

app/helpers/api_forms_helper.rb
Addresses: https://github.com/restarone/violet_rails/issues/1111
=> [Sipshucksip] Cannot create an API resource from admin if has_form is unchecked

app/mailers/api_action_mailer.rb
Addresses: https://github.com/restarone/violet_rails/issues/1357
=> bugfix(): api_resource undefined method fix

app/controllers/comfy/admin/api_namespaces_controller.rb, app/views/comfy/admin/api_namespaces/show.html.haml, test/controllers/admin/comfy/api_namespaces_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1355
Demo: 
https://user-images.githubusercontent.com/55496123/212801008-7a5fdce3-2b22-43d2-956b-9a738ed2dee7.mov
=> [bugfix] dynamic property render in snippets

.github/workflows/brakeman-analysis.yml, .github/workflows/deploy.yml, .github/workflows/dokku-clean-review-apps.yml, .github/workflows/dokku-deploy.yml, .github/workflows/ruby.yml, client/.github/workflows/ci.yml
Addresses: https://github.com/restarone/violet_rails/issues/1362
=> [Violet Rails CI] Update node 12 to node 16 in github actions

.github/workflows/brakeman-analysis.yml, .github/workflows/deploy.yml, .github/workflows/dokku-clean-review-apps.yml, .github/workflows/dokku-deploy.yml, .github/workflows/ruby.yml, client/.github/workflows/ci.yml
Addresses: https://github.com/restarone/violet_rails/issues/1362
=> [CI] Update Node 12 to Node 16 in github actions

.github/workflows/deploy.yml, app/helpers/api_forms_helper.rb, app/views/comfy/admin/api_namespaces/_form.html.haml, test/controllers/admin/comfy/api_resources_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1111
If has_form is unchecked, 
then the form is not rendered
=> [bug fix] non renderable API Namespace unable to create Resources

.github/workflows/deploy.yml, app/mailers/api_action_mailer.rb, app/views/api_action_mailer/send_email.html.erb, test/fixtures/api_actions.yml, test/mailers/api_action_mailer_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1357
Demo: 
https://user-images.githubusercontent.com/55496123/213843605-9ad48e47-2469-4b53-a182-7146f1331f3d.mov
=> [bugfix] api resource undefined method error

app/mailers/api_action_mailer.rb, app/views/api_action_mailer/send_email.html.erb, test/fixtures/api_actions.yml, test/mailers/api_action_mailer_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1357 Demo: 
https://user-images.githubusercontent.com/55496123/213843605-9ad48e47-2469-4b53-a182-7146f1331f3d.mov
=> [bug fix] API resource undefined method error

app/models/concerns/dynamic_attribute.rb, app/models/concerns/safe_executable_validator.rb, test/models/concerns/dynamic_attribute_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1052
Demo:
https://user-images.githubusercontent.com/50227291/188492173-82f9a8ed-609a-44b1-a608-77aa0e1d1600.mov
=> [bug fix] Dynamic links get broken in send_email

app/models/subdomain.rb, app/views/shared/_company_logo.haml, app/views/users/mailer/confirmation_instructions.html.haml, config/sitemap.rb, test/controllers/users/registrations_controller_test.rb, test/models/subdomain_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1375
Demo:
https://user-images.githubusercontent.com/50227291/216375346-430563ab-382e-4c21-a1f5-2aca95f6e4b2.mov
=> [bug fix] Cannot change account email from user settings

app/models/api_namespace.rb, test/models/api_namespace_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1321
**DEMO**
https://user-images.githubusercontent.com/25191509/216947478-5b87efcf-f047-4e44-aca4-63a30ced1fa0.mov
=> [Bug Fix] CMS association not detected when API form is rendered (#1405)

.github/workflows/brakeman-analysis.yml
Addresses : https://github.com/restarone/violet_rails/pull/1382
=> Brakeman Version Update 

app/views/users/sessions/new.html.haml
discovered that sign in is not working on the Violet iOS app
=> enable turbo for sign in

config/schedule.rb, lib/tasks/active_storage.rake, test/tasks/purge_unattached_task_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1083
DEMO:
https://user-images.githubusercontent.com/50227291/219999900-c683255b-018c-4208-8b33-70b541494815.mov
=> purge unattached active storage blob

config/schedule.rb, lib/tasks/active_storage.rake, test/tasks/purge_unattached_task_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1083
DEMO:
https://user-images.githubusercontent.com/50227291/219999900-c683255b-018c-4208-8b33-70b541494815.mov
=> [feature] purge unattached active storage blob

app/controllers/simple_discussion/forum_threads_controller.rb, app/models/forum_thread.rb, app/views/layouts/simple_discussion.html.erb
[forum_search.webm](https://user-images.githubusercontent.com/32646125/224645790-1af561bb-5ec8-4374-962c-702cfa9c6410.webm)
=> Forum search

app/controllers/comfy/admin/v2/dashboard_controller.rb, app/helpers/dashboard_helper.rb, app/models/ahoy/event.rb, test/controllers/admin/comfy/v2/dashboard_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1436
=> [Bug Fix] Undefined method for nil in analytics v2

app/controllers/comfy/admin/cms/layouts_controller.rb, test/controllers/admin/comfy/layouts_controller_test.rb
Addresses: #491 
https://user-images.githubusercontent.com/73725297/226471380-5f6b07d9-8c8c-40ea-a2af-18d42a9f57a3.mp4
=> feat(): use default website layout if no app layout is present

app/controllers/comfy/admin/cms/layouts_controller.rb, test/controllers/admin/comfy/layouts_controller_test.rb
Addresses: #491 
https://user-images.githubusercontent.com/73725297/226471380-5f6b07d9-8c8c-40ea-a2af-18d42a9f57a3.mp4
=> [bug fix] use default website layout if no app layout is present

Gemfile, config/schedule.rb, config/sidekiq.yml, lib/tasks/ahoy.rake, test/tasks/fill_empty_location_entries_task_test.rb
Addresses:
https://github.com/restarone/violet_rails/issues/1473
=> [feature] run ahoy geocoderv2job periodically (#1501)

CONTRIBUTING.md, Gemfile, Gemfile.lock, config/initializers/strong_migrations.rb, db/migrate/20210823235033_add_preview_to_cms_pages.rb
* install strong_migrations
* update contributing doc
=> [feature] install strong_migrations

README.md
=> style: reduce bit typo misspelling README

CONTRIBUTING.md, app/models/ahoy/event.rb, test/controllers/admin/comfy/v2/dashboard_controller_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1524
=> [Bug Fix]: PG::DivisionByZero error in analytics v2

app/assets/stylesheets/api_namespaces.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/comfy/admin/cms/custom.sass, app/controllers/comfy/admin/api_namespaces_controller.rb, app/javascript/controllers/api_namespaces_controller.js, app/javascript/controllers/api_resources_controller.js, app/javascript/controllers/list_view_controller.js, app/views/comfy/admin/api_namespaces/_table.html.haml, app/views/comfy/admin/api_namespaces/api_resources/_index.html.haml, app/views/comfy/admin/api_namespaces/api_resources/_table.html.haml, app/views/comfy/admin/api_namespaces/index.html.haml, test/controllers/admin/comfy/api_namespaces_controller_test.rb
Addresses: #1503 
https://user-images.githubusercontent.com/73725297/230971387-635f4744-4acb-46f7-a056-12a1541a4351.mp4
=> API namespaces list view

app/controllers/cookies_controller.rb, config/initializers/geocoder.rb, test/controllers/cookies_controller_test.rb, test/tasks/fill_empty_location_entries_task_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1559
https://github.com/restarone/violet_rails/assets/25191509/f26ef9a8-c95a-4020-91fc-ea4691b3fbe6
=> [feature]: include geolocation in cookies metadata hash

app/controllers/cookies_controller.rb, config/initializers/geocoder.rb, test/controllers/cookies_controller_test.rb, test/tasks/fill_empty_location_entries_task_test.rb
Addresses: https://github.com/restarone/violet_rails/issues/1559
https://github.com/restarone/violet_rails/assets/25191509/f26ef9a8-c95a-4020-91fc-ea4691b3fbe6
=> [feature] include geolocation in cookies metadata hash

app/controllers/api/external_api_clients_controller.rb, app/models/external_api_client.rb, test/controllers/admin/comfy/external_api_clients_controller_test.rb, test/controllers/api/external_api_clients_controller_test.rb, test/models/external_api_client_test.rb
* reuse already defined model defination call and only unload after change in model
* reuse already defined model defination call and only unload after change in model
* assert class reload
* assert class remove if class name changed
* do not allow save if there's syntax error
* fix test case
* fix test case
* define render only if it doesn't exist
* fix typo
---------
=> [bug fix] Webhook race condition

app/controllers/simple_discussion/forum_threads_controller.rb, app/views/layouts/simple_discussion.html.erb
- add simple form for search
- update of Index action to search the forum if search query present.
=> [feature] add search on forum 

app/controllers/simple_discussion/forum_threads_controller.rb, app/views/layouts/simple_discussion.html.erb
- add simple form for search
- update of Index action to search the forum if search query present.
=> [feature] add search on forum

app/controllers/mailbox/mailbox_controller.rb, app/controllers/mailbox/message_threads_controller.rb, app/helpers/content_helper.rb, app/mailboxes/e_mailbox.rb, app/views/mailbox/mailbox/show.html.haml, app/views/mailbox/message_threads/_index.haml, db/seeds.rb, test/controllers/mailbox/mailbox_controller_test.rb, test/controllers/mailbox/message_threads_controller_test.rb, test/mailboxes/e_mailbox_test.rb
fixes,
- rendering overflow in email list view (list items are now a fixed size)
- sorting when email threads are updated with new messages
=> Email bug fixes august 2023

app/controllers/mailbox/mailbox_controller.rb, app/models/message_thread.rb, test/controllers/mailbox/mailbox_controller_test.rb
Before
```
[16] pry(#<Mailbox::MailboxController>)> @message_threads
MessageThread Load (5.4ms)  SELECT DISTINCT "message_threads".* FROM "message_threads" ORDER BY "message_threads"."unread" DESC, "message_threads"."created_at" DESC LIMIT $1 OFFSET $2  [["LIMIT", 10], ["OFFSET", 0]]
↳ app/controllers/mailbox/mailbox_controller.rb:12:in `show'
Message Load (1.9ms)  SELECT "messages".* FROM "messages" WHERE "messages"."message_thread_id" IN ($1, $2, $3) ORDER BY "messages"."created_at" DESC 
```
After
```
[1] pry(#<Mailbox::MailboxController>)> @message_threads 
SQL (0.8ms)  SELECT DISTINCT "messages"."created_at" AS alias_0, "message_threads"."unread" AS alias_1, "message_threads"."created_at" AS alias_2, "message_threads"."id" FROM "message_threads" INNER JOIN "messages" ON …
```
=> [WIP] fix(): thread order

app/assets/javascripts/libraries/adapter.js, app/channels/application_cable/connection.rb, app/channels/room_channel.rb, app/channels/signaling_channel.rb, app/controllers/comfy/admin/rooms_controller.rb, app/controllers/rooms_controller.rb, app/javascript/controllers/medium_controller.js, app/javascript/controllers/room_controller.js, app/javascript/models/client.js, app/javascript/models/webrtc_negotiation.js, app/javascript/subscriptions/room_subscription.js, app/javascript/subscriptions/signaling_subscription.js, app/models/client.rb, app/models/room.rb, app/views/comfy/admin/cms/partials/_navigation_inner.haml, app/views/layouts/application.html.erb, app/views/media/_medium.html.erb, app/views/rooms/new.html.erb, app/views/rooms/show.html.erb, config/routes.rb
Addresses: https://github.com/restarone/violet_rails/issues/1598
Initialize your room from the Admin panel, 
share the link with participants to join!
It works by peers streaming to, and from each other. For more details and to 
learn about WebRTC, Signalling servers (TURN/STUN) and ICE candidates, see here: https://www.youtube.com/watch?v=WmR9IMUD_CY
guide: https://github.com/domchristie/webrtc-hotwire-rails
Todo's: 
1. ability for participants to mute audio / stop video 
2. fix flakiness in new participants connecting to already-joined peers (newly joined peers dont see existing participants until they refresh the page and join again)
3. UI improvements, see: https://github.com/Alicunde/Videoconference-Dish-CSS-JS
=> [feature] Video Rooms

app/javascript/packs/comfy/admin/cms.js
Addresses: https://github.com/restarone/violet_rails/issues/1609
https://github.com/restarone/violet_rails/assets/25191509/f8368c2b-e072-4b5c-b9e9-bff3ee17c42a
=> [Bug Fix]: tooltip is not a function error in analytics V2 page

app/javascript/controllers/dashboard_controller.js, app/javascript/packs/comfy/admin/cms.js, app/javascript/subscriptions/room_subscription.js, app/javascript/subscriptions/signaling_subscription.js, app/views/comfy/admin/blog/partials/_navigation.html.haml, app/views/comfy/admin/v2/dashboard/dashboard.html.haml, app/views/layouts/comfy/admin/cms.html.haml, app/views/layouts/comfy/admin/cms/_footer_js.html.haml, app/views/layouts/comfy/admin/cms/_head.html.haml, app/views/layouts/comfy/admin/cms/_left.html.haml
Addresses: https://github.com/restarone/violet_rails/issues/1609
https://github.com/restarone/violet_rails/assets/25191509/1adc7ae1-2596-4ffc-92db-cf6f36bf6356
=> [Bug Fix] "tooltip is not a function" in analytics V2

.github/workflows/deploy.yml, .github/workflows/dokku-clean-review-apps.yml, .github/workflows/dokku-deploy.yml, Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/views/comfy/admin/cms/partials/_navigation_inner.haml, app/views/layouts/website.html.erb, config/blazer.yml, config/routes.rb, db/migrate/20241130190941_install_blazer.rb, db/schema.rb
global admins can now access [Blazer](https://github.com/ankane/blazer), for running SQL queries for BI and Data Science purposes:
=> [feature] install blazer
